### ISSUE TITLE
Ansible Failed: python grafana-config-copy.py

### ISSUE THREAD

**Issue by MichelLiu** [pingcap/tidb-ansible#1039]
[172.16.0.241]: Ansible Failed! ==>
  changed=true 
  cmd: python grafana-config-copy.py
  delta: '0:00:00.031137'
  end: '2019-11-19 10:28:29.519474'
  msg: non-zero return code
  rc: 1
  start: '2019-11-19 10:28:29.488337'
  stderr: |2-
      File "grafana-config-copy.py", line 109
        except urllib2.HTTPError, error:
                                ^
    SyntaxError: invalid syntax
  stderr_lines:
  - '  File "grafana-config-copy.py", line 109'
  - '    except urllib2.HTTPError, error:'
  - '                            ^'
  - 'SyntaxError: invalid syntax'
  stdout: ''
  stdout_lines: <omitted>

**Comment by liubo0127** [comment]
Please provide the operation steps and check the `tidb-ansible/scropts/dests.json` file for information such as `user` `url`.

**Comment by MichelLiu** [comment]
python->python3, python2->python2.7 .when I run `ansible-playbook start.yml` command, I always get this error. So I  have changed the following code to resolve my problem. (tidb-ansible-3.0.5)

// grafana-config-copy.py
  try:
        resp = urllib2.urlopen(req)
        data = json.load(resp)
        return data
    except urllib2.HTTPError as error: // replaced ',' with 'as'
        data = json.load(error)
        return data

//start.yml, rolling_update_monitor.yml
- name: import grafana dashboards - run import script
      delegate_to: localhost
      shell: "python2 grafana-config-copy.py" // replaced python with python2
      args:
        chdir: "{{ playbook_dir }}/scripts"
      vars:
        - ansible_become: false
        - ansible_connection: local

**Comment by liubo0127** [comment]
OK, Currently `tidb-ansible` only supports python2.

**Comment by MichelLiu** [comment]
I know that, but specified it with python2 can be better.

**Comment by liubo0127** [comment]
That's right, it can be optimized.

**Comment by liubo0127** [comment]
I will close this issue, feel free to reopen it if has the same problem.
