### ISSUE TITLE
ansible-playbook deploy.yml failure flag provided but not defined: -config-check

### ISSUE THREAD

**Issue by mymilkbottles** [pingcap/tidb-ansible#1042]
version 3.0.2

ansible-playbook deploy.yml fail msg
`{
    "changed":true,
    "cmd":"cd /tmp/tidb_check_config && ./pd-server -config ./pd.toml -config-check",
    "delta":"0:00:00.239820",
    "end":"2019-11-24 21:07:06.356034",
    "msg":"non-zero return code",
    "rc":1,
    "start":"2019-11-24 21:07:06.116214",
    "stderr":"flag provided but not defined: -config-check
Usage of pd:
  -L string
     log level: debug, info, warn, error, fatal (default 'info')
  -V print version information and exit
  -advertise-client-urls string
     advertise url for client traffic (default '${client-urls}')
  -advertise-peer-urls string
     advertise url for peer traffic (default '${peer-urls}')
  -cacert string
     Path of file that contains list of trusted TLS CAs
  -cert string
     Path of file that contains X509 certificate in PEM format
  -client-urls string
     url for client traffic (default "http://127.0.0.1:2379")
  -config string
     Config file
  -data-dir string
     path to the data directory (default 'default.${name}')
  -force-new-cluster
     Force to create a new one-member cluster
  -initial-cluster string
     initial cluster configuration for bootstrapping, e,g. pd=http://127.0.0.1:2380
  -join string
     join to an existing cluster (usage: cluster's '${advertise-client-urls}'
  -key string
     Path of file that contains X509 key in PEM format
  -log-file string
     log file path
  -log-rotate
     rotate log (default true)
  -metrics-addr string
     prometheus pushgateway address, leaves it empty will disable prometheus push.
  -name string
     human-readable name for this pd member
  -namespace-classifier string
     namespace classifier (default 'table') (default "table")
  -peer-urls string
     url for peer traffic (default "http://127.0.0.1:2380")
  -version
     print version information and exit",
    "stderr_lines":[
        "flag provided but not defined: -config-check",
        "Usage of pd:",
        "  -L string",
        "     log level: debug, info, warn, error, fatal (default 'info')",
        "  -V print version information and exit",
        "  -advertise-client-urls string",
        "     advertise url for client traffic (default '${client-urls}')",
        "  -advertise-peer-urls string",
        "     advertise url for peer traffic (default '${peer-urls}')",
        "  -cacert string",
        "     Path of file that contains list of trusted TLS CAs",
        "  -cert string",
        "     Path of file that contains X509 certificate in PEM format",
        "  -client-urls string",
        "     url for client traffic (default "http://127.0.0.1:2379")",
        "  -config string",
        "     Config file",
        "  -data-dir string",
        "     path to the data directory (default 'default.${name}')",
        "  -force-new-cluster",
        "     Force to create a new one-member cluster",
        "  -initial-cluster string",
        "     initial cluster configuration for bootstrapping, e,g. pd=http://127.0.0.1:2380",
        "  -join string",
        "     join to an existing cluster (usage: cluster's '${advertise-client-urls}'",
        "  -key string",
        "     Path of file that contains X509 key in PEM format",
        "  -log-file string",
        "     log file path",
        "  -log-rotate",
        "     rotate log (default true)",
        "  -metrics-addr string",
        "     prometheus pushgateway address, leaves it empty will disable prometheus push.",
        "  -name string",
        "     human-readable name for this pd member",
        "  -namespace-classifier string",
        "     namespace classifier (default 'table') (default "table")",
        "  -peer-urls string",
        "     url for peer traffic (default "http://127.0.0.1:2380")",
        "  -version",
        "     print version information and exit"
    ],
    "stdout":"[2019/11/24 21:07:06.355 +08:00] [FATAL] [main.go:54] ["parse cmd flags error"] [error="flag provided but not defined: -config-check"] [errorVerbose="flag provided but not defined: -config-check\ngithub.com/pingcap/pd/server.(*Config).Parse\n\t/home/jenkins/workspace/release_tidb_3.0/go/src/github.com/pingcap/pd/server/config.go:248\nmain.main\n\t/home/jenkins/workspace/release_tidb_3.0/go/src/github.com/pingcap/pd/cmd/pd-server/main.go:40\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:200\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337"] [stack="github.com/pingcap/log.Fatal\n\t/home/jenkins/workspace/release_tidb_3.0/go/pkg/mod/github.com/pingcap/log@v0.0.0-20190715063458-479153f07ebd/global.go:59\nmain.main\n\t/home/jenkins/workspace/release_tidb_3.0/go/src/github.com/pingcap/pd/cmd/pd-server/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:200"]",
    "stdout_lines":[
        "[2019/11/24 21:07:06.355 +08:00] [FATAL] [main.go:54] ["parse cmd flags error"] [error="flag provided but not defined: -config-check"] [errorVerbose="flag provided but not defined: -config-check\ngithub.com/pingcap/pd/server.(*Config).Parse\n\t/home/jenkins/workspace/release_tidb_3.0/go/src/github.com/pingcap/pd/server/config.go:248\nmain.main\n\t/home/jenkins/workspace/release_tidb_3.0/go/src/github.com/pingcap/pd/cmd/pd-server/main.go:40\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:200\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337"] [stack="github.com/pingcap/log.Fatal\n\t/home/jenkins/workspace/release_tidb_3.0/go/pkg/mod/github.com/pingcap/log@v0.0.0-20190715063458-479153f07ebd/global.go:59\nmain.main\n\t/home/jenkins/workspace/release_tidb_3.0/go/src/github.com/pingcap/pd/cmd/pd-server/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:200"]"
    ]
}`

cd /tmp/tidb_check_config && ./pd-server -config ./pd.toml -config-check
执行命令时报错
手动执行后还是报错：
`./pd-server -config ./pd.toml -config-check
flag provided but not defined: -config-check
Usage of pd:
  -L string
        log level: debug, info, warn, error, fatal (default 'info')
  -V    print version information and exit
  -advertise-client-urls string
        advertise url for client traffic (default '${client-urls}')
  -advertise-peer-urls string
        advertise url for peer traffic (default '${peer-urls}')
  -cacert string
        Path of file that contains list of trusted TLS CAs
  -cert string
        Path of file that contains X509 certificate in PEM format
  -client-urls string
        url for client traffic (default "http://127.0.0.1:2379")
  -config string
        Config file
  -data-dir string
        path to the data directory (default 'default.${name}')
  -force-new-cluster
        Force to create a new one-member cluster
  -initial-cluster string
        initial cluster configuration for bootstrapping, e,g. pd=http://127.0.0.1:2380
  -join string
        join to an existing cluster (usage: cluster's '${advertise-client-urls}'
  -key string
        Path of file that contains X509 key in PEM format
  -log-file string
        log file path
  -log-rotate
        rotate log (default true)
  -metrics-addr string
        prometheus pushgateway address, leaves it empty will disable prometheus push.
  -name string
        human-readable name for this pd member
  -namespace-classifier string
        namespace classifier (default 'table') (default "table")
  -peer-urls string
        url for peer traffic (default "http://127.0.0.1:2380")
  -version
        print version information and exit
[2019/11/24 21:31:14.267 +08:00] [FATAL] [main.go:54] ["parse cmd flags error"] [error="flag provided but not defined: -config-check"] [errorVerbose="flag provided but not defined: -config-check\ngithub.com/pingcap/pd/server.(*Config).Parse\n\t/home/jenkins/workspace/release_tidb_3.0/go/src/github.com/pingcap/pd/server/config.go:248\nmain.main\n\t/home/jenkins/workspace/release_tidb_3.0/go/src/github.com/pingcap/pd/cmd/pd-server/main.go:40\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:200\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337"] [stack="github.com/pingcap/log.Fatal\n\t/home/jenkins/workspace/release_tidb_3.0/go/pkg/mod/github.com/pingcap/log@v0.0.0-20190715063458-479153f07ebd/global.go:59\nmain.main\n\t/home/jenkins/workspace/release_tidb_3.0/go/src/github.com/pingcap/pd/cmd/pd-server/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:200"]`

**Comment by liubo0127** [comment]
The config check function is added in `v3.0.4`. Please try to use the corresponding version of `tidb-ansible` to deploy or manage the cluster.

**Comment by mymilkbottles** [comment]
> The config check function is added in `v3.0.4`. Please try to use the corresponding version of `tidb-ansible` to deploy or manage the cluster.

my problem is, why  `v3.0.2 tidb-ansible`  found  config check function ? bug?

**Comment by liubo0127** [comment]
How do you download the tidb-ansible, according to the method provided by the official website [ansible deployment](https://pingcap.com/docs-cn/stable/how-to/deploy/orchestrated/ansible/#%E5%9C%A8%E4%B8%AD%E6%8E%A7%E6%9C%BA%E5%99%A8%E4%B8%8A%E4%B8%8B%E8%BD%BD-tidb-ansible)?
`git clone -b v3.0.2 https://github.com/pingcap/tidb-ansible.git`

**Comment by liubo0127** [comment]
Please use matched `tidb-version` to install TiDB cluster.
If you want to install TiDB v3.0.2, please use the following methods to download `tidb-ansible`:
- `git clone -b v3.0.2 https://github.com/pingcap/tidb-ansible.git`
- `wget https://github.com/pingcap/tidb-ansible/archive/v3.0.2.tar.gz`

I will close this issue, feel free to reopen it if there are still errors ocurred.
