### ISSUE TITLE
Disable THP when bootstrap

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/tidb-ansible#1078]
There are many customers enable THP and cause many problem. we should disable it
refer: https://www.percona.com/blog/2019/03/06/settling-the-myth-of-transparent-hugepages-for-databases/

**Comment by ethercflow** [comment]
Hi @liubo0127 please make sure THP is disable or always disable by:
 
```
echo never > /sys/kernel/mm/transparent_hugepage/enable
echo never > /sys/kernel/mm/transparent_hugepage/defrag
```

before deploy, no reboot need
