### ISSUE TITLE
"Unable to find '/tidb-ansible-master/downloads/spark-2.1.1-bin-hadoop2.7-all-in-one.tar.gz' in expected paths."

### ISSUE THREAD

**Issue by tshqin** [pingcap/tidb-ansible#112]
I got this msg during the deployment of TiDB cluster by performing the command "ansible-playbook deploy.yml" :
```
TASK [tispark : deploy spark-2.1.1-bin-hadoop2.7] ****************************************************************************************************************************
fatal: [192.168.239.69]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to find '/tidb-ansible-master/downloads/spark-2.1.1-bin-hadoop2.7-all-in-one.tar.gz' in expected paths."}
        to retry, use: --limit @retry_files/deploy.retry

PLAY RECAP *******************************************************************************************************************************************************************
192.168.239.66             : ok=38   changed=14   unreachable=0    failed=0   
192.168.239.67             : ok=38   changed=14   unreachable=0    failed=0   
192.168.239.68             : ok=38   changed=14   unreachable=0    failed=0   
192.168.239.69             : ok=80   changed=35   unreachable=0    failed=1   
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```
I checked this path, there's a file named "spark-2.1.1-bin-hadoop2.7.tar.gz", I'm not sure if it's the needed file, I renamed this file to "spark-2.1.1-bin-hadoop2.7-all-in-one.tar.gz", and it works.
This is a new deployment, the binaries are all new downloaded.

Version:
Release Version: 0.9.0
Git Commit Hash: 9f040b850c3c316d1b99e769104d165a6a426fd8
Git Commit Branch: master
UTC Build Time:  2017-09-06 04:03:17

**Comment by LinuxGit** [comment]
Thanks. We forgot to rename get_url dest name, we've already fixed it. See [fix](https://github.com/pingcap/tidb-ansible/pull/113/files).
