### ISSUE TITLE
Explicitly set old default for user when upgrading tikv?

### ISSUE THREAD

**Issue by yiwu-arbug** [pingcap/tidb-ansible#1126]
@liubo0127 In https://github.com/tikv/tikv/pull/6504 I'm trying to change default value of `rocksdb.defaultcf.block-size` to 4k, but I would like to keep the value to be 64k if the user is upgrading from an old version of tikv with the old default value. Is it possible to do that? If so, it would be great if you can show me how to do it. Thanks!

**Comment by liubo0127** [comment]
This cannot be achieved. `tidb-ansible` uses a template to generate the configuration and it does not know what the `TiKV` configuration in the cluster looks like.

**Comment by yiwu-arbug** [comment]
Got it. I'll try it on tikv side.
