### ISSUE TITLE
Questions about different root passwords in the cluster.

### ISSUE THREAD

**Issue by feloxx** [pingcap/tidb-ansible#1157]
In the doc of `tidb-ansible`.

Step 5. After configuring the `host.ini`, execute `ansible-playbook -i hosts.ini create_users.yml -u root -k` to create users for each host.

But here must be the same root password for each host.

If the root passwords are different, what should i do?

Can this only be the case ([Manually configure ssh mutual trust and sudo password-free](https://pingcap.com/docs-cn/stable/how-to/deploy/orchestrated/ansible/#%E5%A6%82%E4%BD%95%E6%89%8B%E5%B7%A5%E9%85%8D%E7%BD%AE-ssh-%E4%BA%92%E4%BF%A1%E5%8F%8A-sudo-%E5%85%8D%E5%AF%86%E7%A0%81))

**Comment by liubo0127** [comment]
You can edit host.ini as the following format:
```
[servers]
10.0.1.11 ansible_ssh_user=root ansible_ssh_pass='123456'
10.0.1.12 ansible_ssh_user=root ansible_ssh_pass='234567'
10.0.1.13 ansible_ssh_user=root ansible_ssh_pass='123435'
10.0.1.14 ansible_ssh_user=root ansible_ssh_pass='346546'
10.0.1.15 ansible_ssh_user=root ansible_ssh_pass='436547'
10.0.1.16 ansible_ssh_user=root ansible_ssh_pass='436547'

[all:vars]
username = tidb
ntp_server = pool.ntp.org
```

Then run `ansible-playbook -i hosts.ini create_users.yml -u root` to create `tidb` user.

**Comment by feloxx** [comment]
Thank you.
