### ISSUE TITLE
Ending and archiving the tidb-ansible project

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb-ansible#1365]
Ansible Playbook for TiDB is superseded by [TiUP](http://github.com/pingcap/tiup), where the maintainers of tidb-ansible migrated. And there is now a rough consensus to proceed to declare the end of this project.

As tidb-ansible is free software, people are free and welcome to fork and develop the codebase on their own.
However, to avoid any confusion, we intend to archive this project and we recommend any further fork/development to proceed with an explicit rename and rebranding first.

We don't plan to actively delete existing artifacts, but we encourage all interested parties to mirror any relevant bits as we can't actively guarantee their existence in the future.

We should plan a schedule for lazy resolving production problem and announce its retire at a deterministic due.

cc @AstroProfundis @LinuxGit

**Comment by tisonkun** [comment]
@AstroProfundis can we safely archive this repo? If so, please notify @zhouqiang-cl and let's take the action.

**Comment by AstroProfundis** [comment]
Affirmative, it could be archived.
