### ISSUE TITLE
deploy grafana error

### ISSUE THREAD

**Issue by Ishukone** [pingcap/tidb-ansible#146]
hi, start grafana failed when i execute ansible-playbook start.yml.
failed info:
fatal: [10.0.0.28 -> localhost]: FAILED! => {"changed": true, "cmd": "./grafana-config-copy.py", "delta": "0:00:00.051874", "end": "2017-10-19 14:43:30.281220", "failed": true, "rc": 1, "start": "2017-10-19 14:43:30.229346", "stderr": "Traceback (most recent call last):\n  File \"./grafana-config-copy.py\", line 108, in <module>\n    src['dashboards'][type_], type_))\nValueError: zero length field name in format", "stderr_lines": ["Traceback (most recent call last):", "  File \"./grafana-config-copy.py\", line 108, in <module>", "    src['dashboards'][type_], type_))", "ValueError: zero length field name in format"], "stdout": "", "stdout_lines": []}

**Comment by LinuxGit** [comment]
Hi, @Ishukone . What's your Linux OS and python version,  and your tidb-ansible branch?

**Comment by Ishukone** [comment]
Hi,@LinuxGit .
os info:CentOS Linux release 7.2.1511,3.10.0-327.36.3.el7.x86_64
python version:Python 2.7.5
tidb-ansible branch:master
btw:I copy tidb-ansible/scripts to monitor node and execute grafana-config-copy.py is worked.

**Comment by LinuxGit** [comment]
@Ishukone the Control Machine: we recommend CentOS 7.3 or later, and default Python 2.7.5, ansible 2.3.
