### ISSUE TITLE
TASK [machine_benchmark : Preflight check - Does the write speed of tikv deploy_dir disk meet requirement]

### ISSUE THREAD

**Issue by ldbl** [pingcap/tidb-ansible#164]
I'm a bit confused.
`TASK [machine_benchmark : Preflight check - Does the write speed of tikv deploy_dir disk meet requirement] ********************************************************************************************************************************************************************
fatal: [10.148.0.11]: FAILED! => {"changed": false, "failed": true, "msg": "dd: the write speed of tikv deploy_dir disk is too slow: 63,7 MB/s < 15 MB/s"}
fatal: [10.148.0.12]: FAILED! => {"changed": false, "failed": true, "msg": "dd: the write speed of tikv deploy_dir disk is too slow: 62,2 MB/s < 15 MB/s"}
fatal: [10.148.0.14]: FAILED! => {"changed": false, "failed": true, "msg": "dd: the write speed of tikv deploy_dir disk is too slow: 64,9 MB/s < 15 MB/s"}
	to retry, use: --limit @/home/stanfold/tidb/tidb-ansible/retry_files/bootstrap.retry`

What I have to do to to make playbook see that 60 is bigger than 15 ?

**Comment by LinuxGit** [comment]
Hi, @ldbl. What's your Linux destro and os version? Could you provide the output of comand `LANG='en_US.UTF-8' dd bs=4k count=250000 oflag=direct if=/dev/zero of=./dd_test.txt` on your system? It seems that `LANG='en_US.UTF-8'` didn't work properly on your system. And you can skip this task by `changing machine_benchmark = True` to `machine_benchmark = False` in tidb-ansible/inventory.ini.Thanks for your feedback.

**Comment by ldbl** [comment]
Thanks for the reply.
`[tidb@tikv-node1 deploy]$ LANG='en_US.UTF-8' dd bs=4k count=250000 oflag=direct if=/dev/zero of=./dd_test.txt
250000+0 records in
250000+0 records out
1024000000 bytes (1,0 GB) copied, 17,0401 s, 60,1 MB/s
[tidb@tikv-node1 deploy]$ cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 
`
Actually it passes some of the other test I just didn't know why it fails on this.

**Comment by LinuxGit** [comment]
@ldbl Could you provide the output of commands `locale` and  `LANG='en_US.UTF-8' LC_NUMERIC='en_US.UTF-8' dd bs=4k count=250000 oflag=direct if=/dev/zero of=./dd_test.txt` .
It seems that in your country `the comma ,`  is the default decimal separator.Here's my result:
```
1024000000 bytes (1.0 GB) copied, 40.5837 s, 25.2 MB/s
```

**Comment by ldbl** [comment]
Yep that's it.  I just forgot how many time I had issues with this that we have different decimal separator in our country.
Just for info it's google centos image and looks like they preset few things based on your account.
I guess if you add into the ansible command it will work out of the box.
`localectl set-locale LC_NUMERIC="en_US.UTF-8"`

**Comment by LinuxGit** [comment]
Thanks for your feedback. We'll add LC_NUMERIC='en_US.UTF-8' into the command.
