### ISSUE TITLE
Feature Request: save all stderr

### ISSUE THREAD

**Issue by andelf** [pingcap/tidb-ansible#18]
Go program will print goroutine stack to stderr under fatal error, which will bypass log files.
Should redirect stderr in run script. 

To avoid disk space running out, redirect with `>` is acceptable.

Should not use `>>` for append.
Should not append to same log file as main program.

**Comment by LinuxGit** [comment]
已添加 stderr log: https://github.com/pingcap/tidb-ansible/pull/71
