### ISSUE TITLE
-log-slow-query not defined

### ISSUE THREAD

**Issue by gzgzapp** [pingcap/tidb-ansible#198]
in the dir /roles/tidb/templates/run_tidb_binary.sh.j2  line29 -log-slow-query has not defined 
and tidb defined  slow-query-file

**Comment by LinuxGit** [comment]
@gzgzapp Thanks. tidb v1.0.4 doesn't support log-slow-query parameter yet, only master supports it. We've remove it and waiting for cheery pick.
