### ISSUE TITLE
systemd脚本路径不同导致deploy的时候出错

### ISSUE THREAD

**Issue by shavac** [pingcap/tidb-ansible#200]
$ansible-playbook deploy.yml
...
TASK [systemd : create systemd service configuration] ****************************************************************************
fatal: [10.0.0.4]: FAILED! => {"failed": true, "msg": "Failed to get information on remote file (/etc/systemd/system/node_exporter.service): Shared connection to 10.0.0.4 closed.\r\n"}
fatal: [10.0.0.1]: FAILED! => {"failed": true, "msg": "Failed to get information on remote file (/etc/systemd/system/node_exporter.service): Shared connection to 10.0.0.1 closed.\r\n"}
fatal: [10.0.0.2]: FAILED! => {"failed": true, "msg": "Failed to get information on remote file (/etc/systemd/system/node_exporter.service): Shared connection to 10.0.0.2 closed.\r\n"}
fatal: [10.0.0.3]: FAILED! => {"failed": true, "msg": "Failed to get information on remote file (/etc/systemd/system/node_exporter.service): Shared connection to 10.0.0.3 closed.\r\n"}
	to retry, use: --limit @/home/tidb/tidb-ansible/retry_files/deploy.retry

...
$ ls /etc/systemd/system
basic.target.wants  default.target.wants  multi-user.target.wants  sysinit.target.wants
default.target      getty.target.wants    sockets.target.wants     system-update.target.wants

$systemctl show -p FragmentPath sshd
FragmentPath=/usr/lib/systemd/system/sshd.service

$ cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core)

**Comment by LinuxGit** [comment]
@shavac The execution of this playbook requires root privileges. If a password is needed when the normal user gets root privileges from sudo, add the -K (upper case) parameter:
```
ansible-playbook bootstrap.yml -k -K
```
See https://github.com/pingcap/docs-cn/blob/master/op-guide/ansible-deployment.md.

**Comment by LinuxGit** [comment]
I reproduced this error message:
```
TASK [systemd : create systemd service configuration] *******************************************************************************************************
fatal: [172.16.30.5]: FAILED! => {"msg": "Failed to get information on remote file (/etc/systemd/system/node_exporter.service): Shared connection to 172.16.30.5 closed.\r\n"}
changed: [172.16.30.1]
changed: [172.16.30.6]
```

Please run command:
```
ansible-playbook deploy.yml -k -K
```
The execution of this playbook requires root privileges. If a password is needed when the normal user gets root privileges from sudo, add the -K (upper case) parameter.
See https://github.com/pingcap/docs-cn/blob/master/op-guide/ansible-deployment.md.
