### ISSUE TITLE
include_role 引起 role 会对每个host 执行多遍

### ISSUE THREAD

**Issue by lerencao** [pingcap/tidb-ansible#202]
这是 include_role 的bug。 https://github.com/ansible/ansible/issues/18748

issue 中提到可以加 `static: true` 来解决。不知道是否有其他更好的方法。

**Comment by LinuxGit** [comment]
@lerencao Hi, we use include_role without `with_items`, See [include role](https://github.com/pingcap/tidb-ansible/search?p=1&q=include_role&type=&utf8=✓). I tested it on CentOS 7.4.1708 with 2.4.1.0, and there's no issues. What's your ansible and system version?

**Comment by lerencao** [comment]
I am using 2.2 and CentOS 6.9. I'm not sure whether it's fixed in 2.4. Will try it at a later time.

**Comment by LinuxGit** [comment]
@lerencao Thanks your feedback. We recommend CentOS 7.3 and and above, see [Linux OS version requirements](https://github.com/pingcap/docs/blob/master/op-guide/recommendation.md#linux-os-version-requirements). And you need to install Ansible 2.3 or later to your platform, see [Install Ansible in the Control Machine](https://github.com/pingcap/docs/blob/master/op-guide/ansible-deployment.md#install-ansible-in-the-control-machine).

**Comment by lerencao** [comment]
Thanks for the link. Will try it. Close now.
