### ISSUE TITLE
Should we separate preflight-check from check_config_dynamic?

### ISSUE THREAD

**Issue by lerencao** [pingcap/tidb-ansible#203]
Every time we deploy or start or do some other things, preflight-check always run. It slows  down the whole process, when the tikv cluster become large, say 50 nodes.

Maybe it's better to opt out the `check` into a separate role, make the callers choose to run if this is wanted.

**Comment by LinuxGit** [comment]
We'ved added check_config_dynamic and check_config_static roles as the first two tasks in every playbook. Ansible has 5 parallel processes. It will not spend a lot.
