### ISSUE TITLE
grafana config does not support specifying ansible_host

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb-ansible#206]
Due to https://github.com/pingcap/tidb-ansible/blob/70288c9ae8544c8ee2d50a4177a8327085454a08/start.yml#L294  it is now impossible to specify ansible_host for grafana config, like this:

```ini
[grafana_servers]
grafana_my ansible_host=127.0.0.1
```

start will fail because `grafana-config-copy.py` tries to import grafana dashboard to url `http://grafana_my:xxxx` instead of `http://127.0.0.1:xxx`.

similar issues exist in unsafe_restart.yml as well.

**Comment by lerencao** [comment]
Using `ansible_host` can resolve the issue.

**Comment by LinuxGit** [comment]
already fixed it. see https://github.com/pingcap/tidb-ansible/pull/225.
