### ISSUE TITLE
ENV_LABELS_ENV miss ？

### ISSUE THREAD

**Issue by jomenxiao** [pingcap/tidb-ansible#216]
https://github.com/pingcap/tidb-ansible/blob/4db6c32120df4e89a1ea5bcc8b2679156e5ac41a/roles/prometheus/tasks/main.yml#L25

`ENV_LABELS_ENV` cannot find in alert.rules.yml

**Comment by LinuxGit** [comment]
https://github.com/pingcap/tidb-ansible/pull/222
