### ISSUE TITLE
Update grafana to support annotations?

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb-ansible#219]
Grafana 4.6+ brings a new [annotation](http://docs.grafana.org/reference/annotations/) feature, which is very useful. Would like to see it in our dashboards.

**Comment by LinuxGit** [comment]
good,  We'll test grafana 4.6.3.

**Comment by LinuxGit** [comment]
Done, See https://github.com/pingcap/tidb-ansible/pull/223.
