### ISSUE TITLE
deploy prometheus task: create configuration file if not exist failed

### ISSUE THREAD

**Issue by simon-xia** [pingcap/tidb-ansible#24]
when running `ansible-playbook deploy.yml -i inventory.ini` command

got

`fatal: [192.168.1.10]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'node_exporter_port'"}`

**Comment by LinuxGit** [comment]
I suppose you deploy monitoring_servers on host 192.168.1.10. You can add `192.168.1.10` to monitored_servers:children group in inventory.ini, or add `node_exporter_port: 9100` to [all:vars]  in inventory.ini.

**Comment by LinuxGit** [comment]
We've moved node_exporter_port: 9100 variable to all.yml to fix this. You need to use the lastest master branch.
