### ISSUE TITLE
docker安装监控无法检测

### ISSUE THREAD

**Issue by mahb2018** [pingcap/tidb-ansible#243]
修改了docker 的配置文件 依然无法获得数据？？？

例子：

docker run -d --name pd1 \
  --net WHCA --ip 192.168.1.101 \
  -v /etc/localtime:/etc/localtime:ro \
  -v /data:/data \
  -v /data/to/config/pd.toml:/pd.toml:ro \
  pingcap/pd:v1.0.1 \
  --name="pd1" \
  --data-dir="/data/pd1" \
  --client-urls="http://0.0.0.0:2379" \
  --advertise-client-urls="http://192.168.1.101:2379" \
  --peer-urls="http://0.0.0.0:2380" \
  --advertise-peer-urls="http://192.168.1.101:2380" \
  --initial-cluster="pd1=http://192.168.1.101:2380,pd2=http://192.168.1.102:2380,pd3=http://192.168.1.103:2380" \
  --config="/pd.toml"

docker run -d --name tikv1 \
  --net WHCA --ip 192.168.1.104 \
  --ulimit nofile=1000000:1000000 \
  -v /etc/localtime:/etc/localtime:ro \
  -v /data/to/config/tikv.toml:/tikv.toml:ro \
  -v /data:/data \
  pingcap/tikv:v1.0.1  \
  --addr="0.0.0.0:20160" \
  --advertise-addr="192.168.1.104:20160" \
  --data-dir="/data/tikv1" \
  --pd="192.168.1.101:2379,192.168.1.102:2379,192.168.1.103:2379" \
  --config="/tikv.toml"

docker run -d --name tidb \
  --net WHCA --ip 192.168.1.107 \
  -v /etc/localtime:/etc/localtime:ro \
  -v /data/to/config/tidb.toml:/tidb.toml:ro \
  pingcap/tidb:v1.0.1 \
  --store=tikv \
  --path="192.168.1.101:2379,192.168.1.102:2379,192.168.1.103:2379" \
  --config="/tidb.toml"

**Comment by LinuxGit** [comment]
你好，你的 docker 方式安装的集群是通过手工安装还是 Ansible 安装的，目前遇到的问题是监控没有数据？

**Comment by mahb2018** [comment]
今天在prometheus里更改了一下yml配置文件，将prometheus gate way的IP地址和端口 ，填写以后，可以正常使用了，谢谢
