### ISSUE TITLE
bootstrap.yml change my hostname 

### ISSUE THREAD

**Issue by simon-xia** [pingcap/tidb-ansible#25]
The hostname of all host listed in `inventory.ini` has been changed after running `ansible-playbook bootstrap.yml`

The format of changed hostname is:  `ip-192-168-0-1`

**Comment by LinuxGit** [comment]
Yes, there's a task that will set hostname in bootstrap role: https://github.com/pingcap/tidb-ansible/blob/master/roles/bootstrap/tasks/root_tasks.yml .   We'll provide a variable for controlling this and set default value  to False.

**Comment by LinuxGit** [comment]
We've added set_hostname variable in inventory.ini, default value is 'False'. You need to use the lastest master branch.
