### ISSUE TITLE
现有tidb集群加载binlog配置，报错：

### ISSUE THREAD

**Issue by berny9015** [pingcap/tidb-ansible#251]
TASK [stop pump by supervise] ********************************************************************************************************************************************************************************
failed: [172.19.6.1] (item=pump) => {"changed": true, "cmd": "cd /data/tidb/deploy/scripts && ./stop_pump.sh", "delta": "0:00:00.093877", "end": "2018-02-13 10:30:17.364685", "item": "pump", "msg": "non-zero return code", "rc": 127, "start": "2018-02-13 10:30:17.270808", "stderr": "/bin/sh: ./stop_pump.sh: No such file or directory", "stderr_lines": ["/bin/sh: ./stop_pump.sh: No such file or directory"], "stdout": "", "stdout_lines": []}

**Comment by LinuxGit** [comment]
You can reference https://github.com/pingcap/docs-cn/blob/master/tools/tidb-binlog-kafka.md#使用-tidb-ansible-部署-pump. You need to `enable_binlog` in `tidb-ansible/inventory.ini` when running deploy.yml or rolling_update.yml.
