### ISSUE TITLE
 Docker Compose 快速构建集群 报错啦，请大牛们帮忙

### ISSUE THREAD

**Issue by mark-liu-git** [pingcap/tidb-ansible#259]
个人在 VMware 中利用虚拟机，进行集群部署TiDB Docker Compose 安装，报如下错误

4.2.0: Pulling from grafana/grafana
6d827a3ef358: Pull complete
Creating tidbdockercompose_grafana_1             ... done
Creating tidbdockercompose_dashboard-installer_1 ... done
Creating tidbdockercompose_pd2_1                 ... done
Creating tidbdockercompose_pd1_1                 ... done
Creating tidbdockercompose_pd0_1                 ... done
Creating tidbdockercompose_pd1_1                 ...
Creating tidbdockercompose_pd2_1                 ...
Creating tidbdockercompose_pushgateway_1         ...
Creating tidbdockercompose_prometheus_1          ... done
Creating tidbdockercompose_pushgateway_1         ... done
Creating tidbdockercompose_tidb-vision_1         ...
Creating tidbdockercompose_prometheus_1          ...
Creating tidbdockercompose_dashboard-installer_1 ...
Creating tidbdockercompose_tikv2_1               ...
Creating tidbdockercompose_tidb-vision_1         ... done
Creating tidbdockercompose_tikv1_1               ...

ERROR: for tidbdockercompose_tikv1_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for tidbdockercompose_tikv0_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for tidbdockercompose_tikv2_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for tikv2  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for tikv1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for tikv0  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

**Comment by LinuxGit** [comment]
@tennix PTAL

**Comment by wyatt88** [comment]
@mark-liu-git 
请协助提供以下信息，便于我们查找问题：
* OS版本 kernel版本
* docker info的信息
* docker-compose logs的日志信息

多谢

**Comment by wyatt88** [comment]
@mark-liu-git 
这个Issue请提在这里[TiDB docker-compose](https://github.com/pingcap/tidb-docker-compose)，多谢
