### ISSUE TITLE
关于tidb DML语句问题

### ISSUE THREAD

**Issue by aesirteam** [pingcap/tidb-ansible#268]
select user.* from (select 1 union select 2) user limit 1
> 1054 - Unknown table 'user'
> Time: 0.006s

```
select 1 union select 2;
1
---------------
2
---------------
1
```

**Comment by LinuxGit** [comment]
@zhexuany PTAL

**Comment by zhexuany** [comment]
Per error info, it suggests `user` table is not existed.

**Comment by winoros** [comment]
Which tidb version do you use?
I test locally and it works fine.

**Comment by aesirteam** [comment]
@winoros 
version 1.0.8

**Comment by aesirteam** [comment]
@zhexuany  user是别名好吧! 这个dml语句在mysql数据库测试没问题的

**Comment by LinuxGit** [comment]
If discussion is still needed here, please re-open or create a new/updated issue in tidb repo.

**Comment by zhexuany** [comment]
@aesirteam It should already be fixed on tidb's master. I am deeply sorry about my overlooking. You are absolutely right. It is clearly an alias.
