### ISSUE TITLE
ansible启动的时候[import grafana dashboards - run import script] 这个过程报错

### ISSUE THREAD

**Issue by dualc** [pingcap/tidb-ansible#299]
moniter server安装在1921.168.200.192 这个任务在这个ip上执行时就报错，url 404，哪位大佬知道为什么啊
fatal: [192.168.200.192 -> localhost]: FAILED! => {"changed": true, "cmd": "./grafana-config-copy.py", "delta": "0:00:00.085828", "end": "2018-03-14 16:48:53.771198", "msg": "non-zero return code", "rc": 1, "start": "2018-03-14 16:48:53.685370","stderr": "Traceback (most recent call last):\n  File \"./grafana-config-copy.py\", line 119, in <module>\n    ret = import_dashboard_via_user_pass(dest['url'], dest['user'], dest['password'], dashboard)\n  File \"./grafana-config-copy.py\", line 103, in import_dashboard_via_user_pass\n    data = json.load(error)\n  File \"/usr/lib64/python2.7/json/__init__.py\", line 290, in load\n    **kw)\n  File \"/usr/lib64/python2.7/json/__init__.py\", line 338, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/lib64/python2.7/json/decoder.py\", line 366, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/lib64/python2.7/json/decoder.py\", line 384, in raw_decode\n    raise ValueError(\"No JSON object could be decoded\")\nValueError: No JSON object could be decoded", "stderr_lines": ["Traceback (most recent call last):", "  File \"./grafana-config-copy.py\", line 119, in <module>", "    ret = import_dashboard_via_user_pass(dest['url'], dest['user'], dest['password'], dashboard)", "  File \"./grafana-config-copy.py\", line 103, in import_dashboard_via_user_pass", "    data = json.load(error)", "  File \"/usr/lib64/python2.7/json/__init__.py\", line 290, in load", "    **kw)", "  File \"/usr/lib64/python2.7/json/__init__.py\", line 338, in loads", "    return _default_decoder.decode(s)", "  File \"/usr/lib64/python2.7/json/decoder.py\", line 366, in decode", "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())", "  File \"/usr/lib64/python2.7/json/decoder.py\", line 384, in raw_decode", "    raise ValueError(\"No JSON object could be decoded\")", "ValueError: No JSON object could be decoded"], "stdout": "[load] from <node.json>:node\n[import] as <Insight-Tidb-Cluster-Node-Export> to [Insight-Tidb-Cluster]\t............. ", "stdout_lines": ["[load] from <node.json>:node", "[import] as <Insight-Tidb-Cluster-Node-Export> to [Insight-Tidb-Cluster]\t............. "]}

**Comment by LinuxGit** [comment]
您好，请确认 grafana 是否已启动。
```
 sudo systemctl status grafana.service
● grafana.service - grafana service
   Loaded: loaded (/etc/systemd/system/grafana.service; disabled; vendor preset: disabled)
   Active: active (running) since 一 2018-03-05 22:15:53 CST; 1 weeks 2 days ago
```
http://192.168.200.192:3000 是否可访问。

**Comment by dualc** [comment]
确定是ip有问题，访问到别的地方了，问题解决了
