### ISSUE TITLE
直接断电，出现脚本问题，问题可重现

### ISSUE THREAD

**Issue by eachma** [pingcap/tidb-ansible#305]
直接断电后重新 执行start脚本出错

TASK [import grafana dashboards - run import script] ***************************
fatal: [192.168.0.11 -> localhost]: FAILED! => {"changed": true, "cmd": "./grafana-config-copy.py", "delta": "0:00:00.496868", "end": "2018-03-17 20:49:56.367339", "msg": "non-zero return code", "rc": 1, "start": "2018-03-17 20:49:55.870471", "stderr": "Traceback (most recent call last):\n  File \"./grafana-config-copy.py\", line 120, in <module>\n    print(ret['status'])\nKeyError: u'status'", "stderr_lines": ["Traceback (most recent call last):", "  File \"./grafana-config-copy.py\", line 120, in <module>", "    print(ret['status'])", "KeyError: u'status'"], "stdout": "[load] from <node.json>:node\n[import] as <Devcluster-Node-Export> to [Devcluster]\t............. ", "stdout_lines": ["[load] from <node.json>:node", "[import] as <Devcluster-Node-Export> to [Devcluster]\t............. "]}
	to retry, use: --limit @/home/tidb/tidb-ansible/retry_files/start.retry

**Comment by LinuxGit** [comment]
您好，请确认 grafana 是否已启动, http://192.168.0.11:3000 是否可访问。
```
 sudo systemctl status grafana.service
● grafana.service - grafana service
   Loaded: loaded (/etc/systemd/system/grafana.service; disabled; vendor preset: disabled)
   Active: active (running) since 一 2018-03-05 22:15:53 CST; 1 weeks 2 days ago
```

**Comment by eachma** [comment]
已解决。谢谢！

**Comment by wangperry** [comment]
@eachma ，Have the same problem, How to solve it ? thanks
