### ISSUE TITLE
error:Could not find the requested service node_exporter.service: host

### ISSUE THREAD

**Issue by maosim** [pingcap/tidb-ansible#312]
运行ansible-playbook start.yml
时，报：
Ansible FAILED! => playbook: start.yml; TASK: start node_exporter by systemd; message: {"changed": false, "msg": "Could not find the requested service node_exporter.service: host"}
-----------------------------------
我的处女(男？)提就献给你们了

**Comment by LinuxGit** [comment]
Default process_supervision in inventory.ini is systemd:
```
# process supervision, [systemd, supervise]
process_supervision = systemd
```
see https://github.com/pingcap/docs-cn/blob/master/op-guide/ansible-deployment.md#如何调整进程监管方式从-supervise-到-systemd.

You need to run `deploy.yml` before start.yml if you're deploying a new cluster.

**Comment by maosim** [comment]
![tim 20180323110605](https://user-images.githubusercontent.com/13378490/37809443-6385dbb6-2e8a-11e8-8798-27fe7ca379b4.png)

已经是 process_supervision = systemd ，如上图

已经 执行过ansible-playbook deploy.yml，如下图
![tim 20180323110830](https://user-images.githubusercontent.com/13378490/37809536-d5e4e9d6-2e8a-11e8-8ea8-460b7fc940ff.png)

**Comment by maosim** [comment]
解决了。
解决步骤：
ansible-playbook stop.yml
ansible-playbook deploy.yml -D
ansible-playbook start.yml

谢谢。

**Comment by LinuxGit** [comment]
What's your Linux OS version? Could you provide the contents of your inventory.ini?

**Comment by maosim** [comment]
1,
# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.4.1708 (Core) 
Release:        7.4.1708
Codename:       Core

2,
## TiDB Cluster Part
[tidb_servers]
172.16.16.30
172.16.16.38

[tikv_servers]
172.16.16.32
172.16.16.34
172.16.16.36

[pd_servers]
172.16.16.30
172.16.16.38

[spark_master]

[spark_slaves]

## Monitoring Part
# prometheus and pushgateway servers
[monitoring_servers]
172.16.16.30

[grafana_servers]
172.16.16.30

# node_exporter servers
[monitored_servers]
172.16.16.30
172.16.16.32
172.16.16.34
172.16.16.36
172.16.16.38



## Binlog Part
[pump_servers:children]
tidb_servers

## Group variables
[pd_servers:vars]
# location_labels = ["zone","rack","host"]

## Global variables
[all:vars]
deploy_dir = /data/home/tidb/deploy

## Connection
# ssh via normal user
ansible_user = tidb

# ssh via root:
# ansible_user = root
# ansible_become = true
# ansible_become_user = tidb

cluster_name = test-cluster

tidb_version = v1.0.8

# deployment methods, [binary, docker]
deployment_method = binary

# process supervision, [systemd, supervise]
process_supervision = systemd

# timezone of deployment region
timezone = Asia/Shanghai
set_timezone = True

enable_firewalld = False
# check NTP service
enable_ntpd = True
machine_benchmark = True
set_hostname = False

## binlog trigger
enable_binlog = False
# zookeeper address of kafka cluster, example:
# zookeeper_addrs = "192.168.0.11:2181,192.168.0.12:2181,192.168.0.13:2181"
zookeeper_addrs = "172.16.16.30:2181,172.16.16.32:2181,172.16.16.34:2181,172.16.16.36:2181,172.16.16.38:2181"

# KV mode
deploy_without_tidb = False

**Comment by LinuxGit** [comment]
OK. It seems that there's no error in inventory.ini.
