### ISSUE TITLE
Binary download doesn't respect deploy_without_tidb and enable_binlog

### ISSUE THREAD

**Issue by BusyJay** [pingcap/tidb-ansible#332]
After setting deploy_without_tidb to true and enable_binlog to false, local prepare will still download tidb/binlog from remote, which is a waste of time and space.

And there seems no way to disable tispark.

**Comment by LinuxGit** [comment]
OK. I can disable downloading tispark and binlog when setting deploy_without_tidb to true. If not set, we don't provide way to disable tispark now.

**Comment by LinuxGit** [comment]
tidb-ansible master branch has merged the pr: "don't download tispark and binlog when setting deploy_without_tidb = True"
