### ISSUE TITLE
machine_benchmark does not work

### ISSUE THREAD

**Issue by BusyJay** [pingcap/tidb-ansible#333]
It's expected fio benchmark will be skipped when set machine_benchmark to false. However it keeps running task "TASK [machine_benchmark : Benchmark randread iops of deploy_dir disk with fio command]".

**Comment by LinuxGit** [comment]
Sorry, we don't provide way to disable fio test now. We've removed machine_benchmark in master branch.

**Comment by BusyJay** [comment]
I think you need to update documents at https://github.com/pingcap/docs/blob/master/op-guide/ansible-deployment.md#description-of-other-variables

**Comment by LinuxGit** [comment]
Thanks. We've updated English docs.
