### ISSUE TITLE
通过 tidb-ansible 部署后，transparent_hugepage 值与预期不符

### ISSUE THREAD

**Issue by dbalily** [pingcap/tidb-ansible#411]
通过 tidb-ansible 部署后，transparent_hugepage 值与预期不符，预期应该是always，实际是never

**Comment by LinuxGit** [comment]
Ansible sets ulimit and these kernel parameters: https://github.com/pingcap/tidb-ansible/blob/master/roles/bootstrap/tasks/root_tasks.yml#L14. The others are not necessary.
