### ISSUE TITLE
tidb-ansible安装Disk Readahead与预期不符

### ISSUE THREAD

**Issue by dbalily** [pingcap/tidb-ansible#412]
预期不小于4096，实际上看是256，我这边查看方法：/sbin/blockdev --getra /dev/sdc，如果我理解的磁盘预读有问题，可反馈给我，谢谢

**Comment by LinuxGit** [comment]
Ansible sets ulimit and these kernel parameters: https://github.com/pingcap/tidb-ansible/blob/master/roles/bootstrap/tasks/root_tasks.yml#L14. The others are not necessary.
