### ISSUE TITLE
Proposal: Include port number in the PD's systemd service name

### ISSUE THREAD

**Issue by disksing** [pingcap/tidb-ansible#426]
Now we cannot deploy multiple PDs on the same node because of systemd conflict.

**Comment by LinuxGit** [comment]
You can set `process_supervision = supervise` at development stage. We also want to include port number in the PD's systemd service name, but it's a incompatible change. We need to supply a separate playbook for migration, customers will complain.

**Comment by liubo0127** [comment]
Now we support deploy multiple PDs on the same node(use systemd) in 3.0 and later version.
