### ISSUE TITLE
通过ansible启动TIDB时提示API Key文件被拒绝

### ISSUE THREAD

**Issue by vperson** [pingcap/tidb-ansible#428]
TASK [Check grafana API Key list] ********************************************************************************************************************************************************************************************************************************************
ok: [10.1.64.221]

TASK [Check grafana API Key file existed] ************************************************************************************************************************************************************************************************************************************
fatal: [10.1.64.221]: FAILED! => {"changed": false, "msg": "Permission denied"}
	to retry, use: --limit @/home/xiaomai/home/tidb/tidb-ansible.local-ssd/retry_files/start.retry

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************************************
10.1.64.221                : ok=25   changed=5    unreachable=0    failed=1   
172.16.115.40              : ok=14   changed=2    unreachable=0    failed=0   
172.16.115.41              : ok=14   changed=2    unreachable=0    failed=0   
TIDB-1                     : ok=12   changed=1    unreachable=0    failed=0   
TIDB-PD                    : ok=12   changed=1    unreachable=0    failed=0   
TIKV1-1                    : ok=14   changed=1    unreachable=0    failed=0   
TIKV2-1                    : ok=14   changed=1    unreachable=0    failed=0   
TIKV2-2                    : ok=14   changed=1    unreachable=0    failed=0   
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

ERROR MESSAGE SUMMARY ********************************************************************************************************************************************************************************************************************************************************
[10.1.64.221]: Ansible FAILED! => playbook: start.yml; TASK: Check grafana API Key file existed; message: {"changed": false, "msg": "Permission denied"}

**Comment by LinuxGit** [comment]
It reported "Permission denied".  Make sure you put tidb-ansible in `/home/tidb` directory, and the ower permission of tidb-ansible is `tidb` user.  See https://github.com/pingcap/docs-cn/blob/master/op-guide/ansible-deployment.md#在中控机器上下载-tidb-ansible.

**Comment by vperson** [comment]
The tidb-ansible of the central control machine is correct, and it can normally execute operations such as stop deployment, which will cause this problem when starting.The problem should be at the far end

**Comment by LinuxGit** [comment]
@vperson https://github.com/pingcap/tidb-ansible/pull/443 this pr will resolve it. The task will look for grafana key file. If your ssh user doesn't have read permission, it will report error. The pr use local user.
