### ISSUE TITLE
Permission denied (publickey) 

### ISSUE THREAD

**Issue by jiancaiHub** [pingcap/tidb-ansible#436]
执行ssh互信过程中：`ansible-playbook -i hosts.ini create_users.yml -k`

TASK [create user]：
UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added 'ip' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey).\r\n", "unreachable": true}

ERROR MESSAGE SUMMARY：
[172.20.94.35]: Ansible UNREACHABLE! => playbook: create_users.yml; TASK: create user; message: {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added 'ip' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey).\r\n", "unreachable": true}

**Comment by jiancaiHub** [comment]
Must be root?
Is there a non-root way?
I had try to add id_rsa.pub of PD to TiKV machine (/home/tidb/.ssh/id_rsa.pub), but it dose not work.
e.g `ssh tidb@PD` 
result `Permission denied (publickey).`
Is it wrong?

os version：CentOS7

**Comment by LinuxGit** [comment]
Yes, only root can create `tidb` user.
You can also see https://github.com/pingcap/docs-cn/blob/master/op-guide/ansible-deployment.md#如何手工配置-ssh-互信及-sudo-免密码

**Comment by jiancaiHub** [comment]
Generally, we can't have root privileges on the machine of the company.
