### ISSUE TITLE
rollingupdate时，transfering PD leader 最后一个PD失败

### ISSUE THREAD

**Issue by calmzealA** [pingcap/tidb-ansible#438]
从Tidb 1.0.6 升级到 2.0.4
一共3台PD，前面两台执行正常，第3台报错：

TASK [check current PD leader] ******************************************************************************************************************
fatal: [.139]: FAILED! => {"msg": "The conditional check 'pd_leader_info.json.name is defined and pd_leader_info.json.name != pd_name' failed. The error was: error while evaluating conditional (pd_leader_info.json.name is defined and pd_leader_info.json.name != pd_name): 'dict object' has no attribute 'json'"}

直接
curl -X POST http://xxx.139:2379/pd/api/v1/leader/resign
返回null
然后 curl http://xxx.139:2379/pd/api/v1/leader
返回no leader
等几秒，再次执行curl http://10.155.111.139:2379/pd/api/v1/leader
返回的 pd还是当前这台
curl http://10.155.111.136:2379/pd/api/v1/leader
{
  "name": "pd3",
  "member_id": 6795350017215450226,
  "peer_urls": [
    "http://xxx.139:2380"
  ],
  "client_urls": [
    "http://xxx.139:2379"
  ]
}

应该怎么处理？ 谢谢！

**Comment by LinuxGit** [comment]
Run `member` and `health` commond in pd-ctl console. Are the other pd nodes online?
```
$ /home/tidb/tidb-ansible/resources/bin/pd-ctl -u "http://172.16.10.72:2379"
» member
{
  "header": {
    "cluster_id": 6561282423466574739
  },
  "members": [
    {
      "name": "pd3",
      "member_id": 3325137909413941222,
      "peer_urls": [
        "http://172.16.10.74:2380"
      ],
      "client_urls": [
        "http://172.16.10.74:2379"
      ]
    },
    {
      "name": "pd2",
      "member_id": 4943792828990837729,
      "peer_urls": [
        "http://172.16.10.73:2380"
      ],
      "client_urls": [
        "http://172.16.10.73:2379"
      ]
    },
    {
      "name": "pd1",
      "member_id": 16211937181177432157,
      "peer_urls": [
        "http://172.16.10.72:2380"
      ],
      "client_urls": [
        "http://172.16.10.72:2379"
      ]
    }
  ],
  "leader": {
    "name": "pd1",
    "member_id": 16211937181177432157,
    "peer_urls": [
      "http://172.16.10.72:2380"
    ],
    "client_urls": [
      "http://172.16.10.72:2379"
    ]
  },
  "etcd_leader": {
    "name": "pd1",
    "member_id": 16211937181177432157,
    "peer_urls": [
      "http://172.16.10.72:2380"
    ],
    "client_urls": [
      "http://172.16.10.72:2379"
    ]
  }
}

» health
[
  {
    "name": "pd3",
    "member_id": 3325137909413941222,
    "client_urls": [
      "http://172.16.10.74:2379"
    ],
    "health": true
  },
  {
    "name": "pd2",
    "member_id": 4943792828990837729,
    "client_urls": [
      "http://172.16.10.73:2379"
    ],
    "health": true
  },
  {
    "name": "pd1",
    "member_id": 16211937181177432157,
    "client_urls": [
      "http://172.16.10.72:2379"
    ],
    "health": true
  }
]
```

**Comment by calmzealA** [comment]
@LinuxGit 
谢谢
已经处理好了。

pd-ctl里面member显示3个pd正常，health当时报错404。

主要的问题在于每次选举leader都是pd3，可能跟pd1,pd2已经升级到2.0.4,pd3还是1.0.6有关。
然后我们采用下面的方法绕过了：
1. 手动停掉 pd3。 这时候leader能切换到pd1。
2. 修改inventory.ini，在PD list 配置里面，将PD3 放在第一个。（否则，再次执行rolling update，还是会从pd1，pd2开始升级，这样会将leader再切到pd3.）
3. 执行升级。
