### ISSUE TITLE
Feature request: add location label to tikv to allow location awareness scheduling

### ISSUE THREAD

**Issue by tennix** [pingcap/tidb-ansible#44]
PD and TiKV support [location awareness scheduling](https://github.com/pingcap/docs/blob/master/op-guide/location-awareness.md) which improves tidb cluster's availability. This should be supported in tidb-ansible too

**Comment by LinuxGit** [comment]
You can edit inventory.ini add lables:
For example:
[pd_servers:vars]
location_labels = ["host"]

tikv1 ansible_host=172.16.10.2 labels="host=h1"
