### ISSUE TITLE
Does TiDB support suse12 OS?

### ISSUE THREAD

**Issue by wuzhanpeng** [pingcap/tidb-ansible#471]
Hi, could TiDB be deployed in suse12? Has anyone tested on it?

**Comment by LinuxGit** [comment]
TiDB supports most of the major hardware networks and Linux operating systems. But we tested it on CentOS 7 a lot, see https://github.com/pingcap/docs/blob/master/op-guide/recommendation.md.
And it's recommended to use tidb-ansible on CentOS 7.
