### ISSUE TITLE
ttt

### ISSUE THREAD

**Issue by lyddragon** [pingcap/tidb-ansible#472]
解压第三方二进制包时报错，输出错误：ls: cannot access prometheus-2.2.1.tar.gz: No such file or directory

**Comment by LinuxGit** [comment]
```
ansible-playbook local_prepare.yml
```
Hi, you can run the `local_prepare.yml` playbook again, if there's no errors, it will download prometheus-2.2.1.tar.gz to the Control Machine `/home/tidb/tidb-ansible/downloads` directory.
