### ISSUE TITLE
Timeout when waiting for search string 200 OK in x.x.x.x:2379

### ISSUE THREAD

**Issue by gutongjiang** [pingcap/tidb-ansible#479]
TASK [wait for PD up] **************************************************************************************************************

fatal: [172.31.31.84]: FAILED! => {"changed": false, "elapsed": 301, "msg": "Timeout when waiting for search string 200 OK in 172.31.31.84:2379"}
fatal: [172.31.28.135]: FAILED! => {"changed": false, "elapsed": 301, "msg": "Timeout when waiting for search string 200 OK in 172.31.28.135:2379"}
fatal: [172.31.27.177]: FAILED! => {"changed": false, "elapsed": 301, "msg": "Timeout when waiting for search string 200 OK in 172.31.27.177:2379"}
	to retry, use: --limit @/home/tidb/tidb-ansible/retry_files/start.retry

and the inventory.ini

## TiDB Cluster Part
[tidb_servers]
172.31.26.89
172.31.30.15

[tikv_servers]
172.31.27.92
172.31.19.224
172.31.25.190

[pd_servers]
172.31.28.135
172.31.27.177
172.31.31.84

[spark_master]

[spark_slaves]

## Monitoring Part
# prometheus and pushgateway servers
[monitoring_servers]
172.31.24.4

[grafana_servers]
172.31.24.4

# node_exporter and blackbox_exporter servers
[monitored_servers]
172.31.28.135
172.31.27.177
172.31.31.84
172.31.26.89
172.31.30.15
172.31.27.92
172.31.19.224
172.31.25.190

[alertmanager_servers]
## 172.31.24.4

[kafka_exporter_servers]

## Binlog Part
[pump_servers:children]
tidb_servers

[drainer_servers]

## Group variables
[pd_servers:vars]
# location_labels = ["zone","rack","host"]

## Global variables
[all:vars]
deploy_dir = /data1/deploy

## Connection
# ssh via normal user
ansible_user = tidb

cluster_name = test-cluster

tidb_version = v2.0.5

# process supervision, [systemd, supervise]
process_supervision = systemd

# timezone of deployment region
timezone = Asia/Shanghai
set_timezone = True

enable_firewalld = False
# check NTP service
enable_ntpd = True
set_hostname = False
# CPU, memory and disk performance will not be checked when dev_mode = True
dev_mode = False

## binlog trigger
enable_binlog = False
# zookeeper address of kafka cluster for binlog, example:
# zookeeper_addrs = "192.168.0.11:2181,192.168.0.12:2181,192.168.0.13:2181"
zookeeper_addrs = ""
# kafka cluster address for monitoring, example:
# kafka_addrs = "192.168.0.11:9092,192.168.0.12:9092,192.168.0.13:9092"
kafka_addrs = ""

# store slow query log into seperate file
enable_slow_query_log = False

# enable TLS authentication in the TiDB cluster
enable_tls = False

# KV mode
deploy_without_tidb = False

# Optional: Set if you already have a alertmanager server.
# Format: alertmanager_host:alertmanager_port
alertmanager_target = ""

grafana_admin_user = "admin"
grafana_admin_password = "admin"

### Collect diagnosis
collect_log_recent_hours = 2

enable_bandwidth_limit = True
# default: 10Mb/s, unit: Kbit/s
collect_bandwidth_limit = 10000

**Comment by LinuxGit** [comment]
You could see the logs of pd nodes: ` /data1/deploy/log/pd.log` and provide the error messages.

**Comment by gutongjiang** [comment]
2018/07/31 11:41:49.624 log.go:86: [info] raft: [8688be825db2c9b9 is starting a new election at term 12151]
2018/07/31 11:41:49.624 log.go:86: [info] raft: [8688be825db2c9b9 became candidate at term 12152]
2018/07/31 11:41:49.624 log.go:86: [info] raft: [8688be825db2c9b9 received MsgVoteResp from 8688be825db2c9b9 at term 12152]
2018/07/31 11:41:49.624 log.go:86: [info] raft: [8688be825db2c9b9 [logterm: 1, index: 3] sent MsgVote request to 7953c696449e9419 at term 12152]
2018/07/31 11:41:49.624 log.go:86: [info] raft: [8688be825db2c9b9 [logterm: 1, index: 3] sent MsgVote request to 744264351e7e485 at term 12152]
2018/07/31 11:41:51.281 log.go:80: [error] etcdserver: [publish error: etcdserver: request timed out]
2018/07/31 11:41:52.139 log.go:82: [warning] rafthttp: [health check for peer 7953c696449e9419 could not connect: dial tcp 172.31.27.177:2380: i/o timeout]
2018/07/31 11:41:52.139 log.go:82: [warning] rafthttp: [health check for peer 744264351e7e485 could not connect: dial tcp 172.31.31.84:2380: i/o timeout]
2018/07/31 11:41:53.624 log.go:86: [info] raft: [8688be825db2c9b9 is starting a new election at term 12152]
2018/07/31 11:41:53.624 log.go:86: [info] raft: [8688be825db2c9b9 became candidate at term 12153]
2018/07/31 11:41:53.624 log.go:86: [info] raft: [8688be825db2c9b9 received MsgVoteResp from 8688be825db2c9b9 at term 12153]
2018/07/31 11:41:53.624 log.go:86: [info] raft: [8688be825db2c9b9 [logterm: 1, index: 3] sent MsgVote request to 744264351e7e485 at term 12153]
2018/07/31 11:41:53.624 log.go:86: [info] raft: [8688be825db2c9b9 [logterm: 1, index: 3] sent MsgVote request to 7953c696449e9419 at term 12153]
2018/07/31 11:41:56.662 metricutil.go:73: [error] could not push metrics to Prometheus Pushgateway: Put http://172.31.24.4:9091/metrics/job/pd1/instance/ip-172-31-28-135: dial tcp 172.31.24.4:9091: i/o timeout
2018/07/31 11:41:57.124 log.go:86: [info] raft: [8688be825db2c9b9 is starting a new election at term 12153]
2018/07/31 11:41:57.124 log.go:86: [info] raft: [8688be825db2c9b9 became candidate at term 12154]
2018/07/31 11:41:57.124 log.go:86: [info] raft: [8688be825db2c9b9 received MsgVoteResp from 8688be825db2c9b9 at term 12154]
2018/07/31 11:41:57.124 log.go:86: [info] raft: [8688be825db2c9b9 [logterm: 1, index: 3] sent MsgVote request to 744264351e7e485 at term 12154]
2018/07/31 11:41:57.124 log.go:86: [info] raft: [8688be825db2c9b9 [logterm: 1, index: 3] sent MsgVote request to 7953c696449e9419 at term 12154]
2018/07/31 11:41:57.139 log.go:82: [warning] rafthttp: [health check for peer 7953c696449e9419 could not connect: dial tcp 172.31.27.177:2380: i/o timeout]
2018/07/31 11:41:57.139 log.go:82: [warning] rafthttp: [health check for peer 744264351e7e485 could not connect: dial tcp 172.31.31.84:2380: i/o timeout]
2018/07/31 11:42:02.140 log.go:82: [warning] rafthttp: [health check for peer 744264351e7e485 could not connect: dial tcp 172.31.31.84:2380: i/o timeout]
2018/07/31 11:42:02.140 log.go:82: [warning] rafthttp: [health check for peer 7953c696449e9419 could not connect: dial tcp 172.31.27.177:2380: i/o timeout]
2018/07/31 11:42:02.281 log.go:80: [error] etcdserver: [publish error: etcdserver: request timed out]
2018/07/31 11:42:02.624 log.go:86: [info] raft: [8688be825db2c9b9 is starting a new election at term 12154]
2018/07/31 11:42:02.624 log.go:86: [info] raft: [8688be825db2c9b9 became candidate at term 12155]
2018/07/31 11:42:02.624 log.go:86: [info] raft: [8688be825db2c9b9 received MsgVoteResp from 8688be825db2c9b9 at term 12155]
2018/07/31 11:42:02.624 log.go:86: [info] raft: [8688be825db2c9b9 [logterm: 1, index: 3] sent MsgVote request to 7953c696449e9419 at term 12155]
2018/07/31 11:42:02.624 log.go:86: [info] raft: [8688be825db2c9b9 [logterm: 1, index: 3] sent MsgVote request to 744264351e7e485 at term 12155]
2018/07/31 11:42:06.124 log.go:86: [info] raft: [8688be825db2c9b9 is starting a new election at term 12155]
2018/07/31 11:42:06.124 log.go:86: [info] raft: [8688be825db2c9b9 became candidate at term 12156]
2018/07/31 11:42:06.124 log.go:86: [info] raft: [8688be825db2c9b9 received MsgVoteResp from 8688be825db2c9b9 at term 12156]
2018/07/31 11:42:06.124 log.go:86: [info] raft: [8688be825db2c9b9 [logterm: 1, index: 3] sent MsgVote request to 744264351e7e485 at term 12156]
2018/07/31 11:42:06.124 log.go:86: [info] raft: [8688be825db2c9b9 [logterm: 1, index: 3] sent MsgVote request to 7953c696449e9419 at term 12156]
2018/07/31 11:42:07.140 log.go:82: [warning] rafthttp: [health check for peer 744264351e7e485 could not connect: dial tcp 172.31.31.84:2380: i/o timeout]
2018/07/31 11:42:07.140 log.go:82: [warning] rafthttp: [health check for peer 7953c696449e9419 could not connect: dial tcp 172.31.27.177:2380: i/o timeout]
2018/07/31 11:42:09.124 log.go:86: [info] raft: [8688be825db2c9b9 is starting a new election at term 12156]
2018/07/31 11:42:09.124 log.go:86: [info] raft: [8688be825db2c9b9 became candidate at term 12157]
2018/07/31 11:42:09.124 log.go:86: [info] raft: [8688be825db2c9b9 received MsgVoteResp from 8688be825db2c9b9 at term 12157]
2018/07/31 11:42:09.124 log.go:86: [info] raft: [8688be825db2c9b9 [logterm: 1, index: 3] sent MsgVote request to 7953c696449e9419 at term 12157]
2018/07/31 11:42:09.124 log.go:86: [info] raft: [8688be825db2c9b9 [logterm: 1, index: 3] sent MsgVote request to 744264351e7e485 at term 12157]
2018/07/31 11:42:12.140 log.go:82: [warning] rafthttp: [health check for peer 744264351e7e485 could not connect: dial tcp 172.31.31.84:2380: i/o timeout]
2018/07/31 11:42:12.140 log.go:82: [warning] rafthttp: [health check for peer 7953c696449e9419 could not connect: dial tcp 172.31.27.177:2380: i/o timeout]
2018/07/31 11:42:12.624 log.go:86: [info] raft: [8688be825db2c9b9 is starting a new election at term 12157]
2018/07/31 11:42:12.624 log.go:86: [info] raft: [8688be825db2c9b9 became candidate at term 12158]
2018/07/31 11:42:12.624 log.go:86: [info] raft: [8688be825db2c9b9 received MsgVoteResp from 8688be825db2c9b9 at term 12158]
2018/07/31 11:42:12.624 log.go:86: [info] raft: [8688be825db2c9b9 [logterm: 1, index: 3] sent MsgVote request to 744264351e7e485 at term 12158]
2018/07/31 11:42:12.624 log.go:86: [info] raft: [8688be825db2c9b9 [logterm: 1, index: 3] sent MsgVote request to 7953c696449e9419 at term 12158]
2018/07/31 11:42:13.281 log.go:80: [error] etcdserver: [publish error: etcdserver: request timed out]
2018/07/31 11:42:15.624 log.go:86: [info] raft: [8688be825db2c9b9 is starting a new election at term 12158]
2018/07/31 11:42:15.624 log.go:86: [info] raft: [8688be825db2c9b9 became candidate at term 12159]
2018/07/31 11:42:15.624 log.go:86: [info] raft: [8688be825db2c9b9 received MsgVoteResp from 8688be825db2c9b9 at term 12159]
2018/07/31 11:42:15.624 log.go:86: [info] raft: [8688be825db2c9b9 [logterm: 1, index: 3] sent MsgVote request to 744264351e7e485 at term 12159]
2018/07/31 11:42:15.624 log.go:86: [info] raft: [8688be825db2c9b9 [logterm: 1, index: 3] sent MsgVote request to 7953c696449e9419 at term 12159]
2018/07/31 11:42:17.140 log.go:82: [warning] rafthttp: [health check for peer 744264351e7e485 could not connect: dial tcp 172.31.31.84:2380: i/o timeout]
2018/07/31 11:42:17.140 log.go:82: [warning] rafthttp: [health check for peer 7953c696449e9419 could not connect: dial tcp 172.31.27.177:2380: i/o timeout]

**Comment by LinuxGit** [comment]
"could not connect: dial tcp 172.31.27.177:2380: i/o timeout"
Please check your firewall and if pd instance on 172.31.27.177 is running.
