### ISSUE TITLE
Tidb-ansible failed to deploy tidb to AWS EC2 instances (i3.4xlarge)

### ISSUE THREAD

**Issue by jaltabike** [pingcap/tidb-ansible#521]
Because of the recent change on tidb-ansible(#513),
I failed to deploy tidb to AWS EC2 instances (i3.4xlarge, which uses NVMe) by using tidb-ansible as follows:

fatal: [tikv1]: FAILED! => {"changed": false, "msg": "fio mixed randread and sequential write test: randread iops of  tikv_data_dir disk is too low: 8606 < 10000, it is strongly recommended to use SSD disks for TiKV and PD, or there might be performance issues."}

In the recent change(#513),
the value of min_ssd_mix_randread_iops has been changed from 4000 to 10000.
The result of fio test ("fio mixed randread and sequential write") on AWS EC2 instances was about 8000.
Does AWS EC2 instance equipped with NVMe realy not meet the tidb's minimum specification?
Or, is not the minimum specification too high in the recent change?

**Comment by LinuxGit** [comment]
Thanks for your feedback.
You can run `ansible-playbook bootstrap.yml --extra-vars "dev_mode=True"` to skip disk performance  benchmark.
The baseline is the benchmark result of Intel DC S3610 SATA3 SSD on physical machine, and NVMe SSD is recommended.
We changed fio ioengine from libaio to psync, so we adjusted the baseline iops and latency.

**Comment by jaltabike** [comment]
Thank you for your answer, @LinuxGit 
By the way, for "practical use" (not "dev_mode"), it sounds that it is not recommended to run/operate tidb on AWS EC2 instances with NVMe SSD (which is the fastest disk provided by AWS) because tidb-ansible without "dev_mode=True" option fails to deploy tidb on such AWS EC2 instances.
AWS EC2 is very commonly used to operate various systems including DBMS, but tidb seems to be impractical.
Is it really not recommended to run/operate tidb on AWS EC2 instances with NVMe SSD for "practical use" (not for dev)?
Or, is there any possibility that the minimum specification such as min_ssd_mix_randread_iops adjusted in the future?

**Comment by LinuxGit** [comment]
We have been in touch with Samsung. To communicate more effectively, you can contact us via info@pingcap.com. We'll consider using Slack or something like that.

**Comment by LinuxGit** [comment]
@jaltabike Thanks. We're investigating why the result of fio mixed randread and sequential write benchmark on NVMe SSD of Cloud is slower than SATA3 SSD on physical machine.

**Comment by LinuxGit** [comment]
Hi, @jaltabike What's your OS version of i3.4xlarge instance?

**Comment by jaltabike** [comment]
@LinuxGit 
Ubuntu Server 16.04

**Comment by LinuxGit** [comment]
Thank you for your continued patience.

Here's our Intel P4500 4T NVMe SSD result on physical machine. (CentOS 7, ext4):
read: IOPS=15635
lat (ns): min=3360, max=5359216, avg=158927
clat percentiles (ns): 95.00th=610304, 99.00th=1056768
write: IOPS=15669
lat (ns): min=7563, max=259461, avg=22959
clat percentiles (ns): 95.00th=45312, 99.00th=58624

i3.2xlarge's result using Amazon Linux 2 AMI image:
jobname: fio mixed randread and sequential write test
read: IOPS=7293
lat (ns): min=3554, max=4250804, avg=393834
clat percentiles (ns): 95.00th=2375680, 99.00th=3194880
write: IOPS=7298
lat (ns): min=8595, max=1847590, avg=21780
clat percentiles (ns): 95.00th=41216, 99.00th=52480

Our benchmark command is:
```
fio -ioengine=psync -bs=32k -fdatasync=1 -thread -rw=randrw -percentage_random=100,0 -size=10G -filename=fio_randread_write_test.txt -name='fio mixed randread and sequential write test' -iodepth=4 -runtime=60 -numjobs=4 -group_reporting
```

AWS support center suggest that we should not compare i3's NVMe devices with any On-prem disk. 

i3's NVMe SSD preformance is greater than other instances, It's a better choice on AWS, but NVMe on physical machine will get better performace.

If you are still experiencing this issue, please reopen this issue.
