### ISSUE TITLE
Timeout: wait for TiDB up

### ISSUE THREAD

**Issue by gutongjiang** [pingcap/tidb-ansible#522]
ansible-playbook start.yml

[172.31.26.89]: Ansible FAILED! => playbook: start.yml; TASK: wait for TiDB up; message: {"changed": false, "elapsed": 300, "msg": "Timeout when waiting for search string TiDB in 172.31.26.89:10080"}
[172.31.30.15]: Ansible FAILED! => playbook: start.yml; TASK: wait for TiDB up; message: {"changed": false, "elapsed": 300, "msg": "Timeout when waiting for search string TiDB in 172.31.30.15:10080"}

and the log:
2018/09/04 14:35:55.293 printer.go:38: [info] Welcome to TiDB.
2018/09/04 14:35:55.293 printer.go:39: [info] Release Version: v2.0.5
2018/09/04 14:35:55.293 printer.go:40: [info] Git Commit Hash: 43ab80012ae6a154e221e124a2ad3a396f0de822
2018/09/04 14:35:55.293 printer.go:41: [info] Git Branch: release-2.0
2018/09/04 14:35:55.293 printer.go:42: [info] UTC Build Time:  2018-07-06 08:52:37
2018/09/04 14:35:55.293 printer.go:43: [info] GoVersion:  go version go1.10.2 linux/amd64
2018/09/04 14:35:55.293 printer.go:44: [info] TiKV Min Version: 2.0.0-rc.4.1
2018/09/04 14:35:55.293 printer.go:49: [info] Config: {"host":"0.0.0.0","port":4000,"store":"tikv","path":"172.31.27.177:2379,172.31.31.84:2379","socket":"","lease":"45s","run-ddl":true,"split-table":true,"token-limit":1000,"oom-action":"log","mem-quota-query":34359738368,"enable-streaming":false,"lower-case-table-names":2,"log":{"level":"info","format":"text","disable-timestamp":false,"file":{"filename":"/data1/deploy/log/tidb.log","log-rotate":true,"max-size":300,"max-days":0,"max-backups":0},"slow-query-file":"","slow-threshold":300,"expensive-threshold":10000,"query-log-max-len":2048},"security":{"skip-grant-table":false,"ssl-ca":"","ssl-cert":"","ssl-key":"","cluster-ssl-ca":"","cluster-ssl-cert":"","cluster-ssl-key":""},"status":{"report-status":true,"status-port":10080,"metrics-addr":"172.31.24.4:9091","metrics-interval":15},"performance":{"max-procs":0,"tcp-keep-alive":true,"retry-limit":10,"cross-join":true,"stats-lease":"3s","run-auto-analyze":true,"stmt-count-limit":5000,"feedback-probability":0,"query-feedback-limit":1024,"pseudo-estimate-ratio":0.7},"xprotocol":{"xserver":false,"xhost":"","xport":0,"xsocket":""},"plan-cache":{"enabled":false,"capacity":2560,"shards":256},"prepared-plan-cache":{"enabled":false,"capacity":100},"opentracing":{"enbale":false,"sampler":{"type":"const","param":1,"sampling-server-url":"","max-operations":0,"sampling-refresh-interval":0},"reporter":{"queue-size":0,"buffer-flush-interval":0,"log-spans":false,"local-agent-host-port":""},"rpc-metrics":false},"proxy-protocol":{"networks":"","header-timeout":5},"tikv-client":{"grpc-connection-count":16,"commit-timeout":"41s"},"binlog":{"binlog-socket":"","write-timeout":"15s","ignore-error":false}}
2018/09/04 14:35:55.293 main.go:193: [info] start Prometheus push client with server addr 172.31.24.4:9091 and interval 15s
2018/09/04 14:35:55.293 tidb.go:279: [info] new store
2018/09/04 14:35:55.293 client.go:114: [info] [pd] create pd client with endpoints [172.31.27.177:2379 172.31.31.84:2379]
2018/09/04 14:35:55.293 systime_mon.go:24: [info] start system time monitor
2018/09/04 14:35:55.299 client.go:212: [info] [pd] leader switches to: http://172.31.31.84:2379, previous:
2018/09/04 14:35:55.299 client.go:133: [info] [pd] init cluster id 6584223375836839082
2018/09/04 14:35:55.303 tidb.go:64: [info] store tikv-6584223375836839082 new domain, ddl lease 45s, stats lease 3000000000
2018/09/04 14:35:55.304 ddl.go:292: [info] [ddl] start delRangeManager OK, with emulator: false
2018/09/04 14:35:55.305 ddl.go:300: [info] [ddl] start DDL:ee14c7d9-bfc7-48c1-8e9c-8f2c2c9bc43f
2018/09/04 14:35:55.305 ddl_worker.go:71: [info] [ddl] cleaning jobs in the adding index queue finished.
2018/09/04 14:35:55.346 domain.go:117: [info] [ddl] full load InfoSchema from version 0 to 1093, in 35.360965ms
2018/09/04 14:35:55.347 domain.go:309: [info] [ddl] full load and reset schema validator.
2018/09/04 14:35:56.058 coprocessor.go:689: [info] [TIME_COP_PROCESS] resp_time:400.48847ms txn_start_ts:402664444484124677 region_id:27 store_addr:172.31.19.224:20160 backoff_ms:700 backoff_types:[regionMiss,regionMiss,regionMiss]
2018/09/04 14:35:57.059 coprocessor.go:689: [info] [TIME_COP_PROCESS] resp_time:500.461919ms txn_start_ts:402664444484124677 region_id:27 store_addr:172.31.19.224:20160 backoff_ms:1700 backoff_types:[regionMiss,regionMiss,regionMiss,regionMiss,regionMiss]
2018/09/04 14:35:58.060 coprocessor.go:689: [info] [TIME_COP_PROCESS] resp_time:500.499468ms txn_start_ts:402664444484124677 region_id:27 store_addr:172.31.19.224:20160 backoff_ms:2700 backoff_types:[regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss]
2018/09/04 14:35:59.061 coprocessor.go:689: [info] [TIME_COP_PROCESS] resp_time:500.517546ms txn_start_ts:402664444484124677 region_id:27 store_addr:172.31.19.224:20160 backoff_ms:3700 backoff_types:[regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss]
2018/09/04 14:36:00.063 coprocessor.go:689: [info] [TIME_COP_PROCESS] resp_time:500.537179ms txn_start_ts:402664444484124677 region_id:27 store_addr:172.31.19.224:20160 backoff_ms:4700 backoff_types:[regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss]
2018/09/04 14:36:01.064 coprocessor.go:689: [info] [TIME_COP_PROCESS] resp_time:500.525179ms txn_start_ts:402664444484124677 region_id:27 store_addr:172.31.19.224:20160 backoff_ms:5700 backoff_types:[regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss]
2018/09/04 14:36:02.065 coprocessor.go:689: [info] [TIME_COP_PROCESS] resp_time:500.552544ms txn_start_ts:402664444484124677 region_id:27 store_addr:172.31.19.224:20160 backoff_ms:6700 backoff_types:[regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss]
2018/09/04 14:36:03.066 coprocessor.go:689: [info] [TIME_COP_PROCESS] resp_time:500.474053ms txn_start_ts:402664444484124677 region_id:27 store_addr:172.31.19.224:20160 backoff_ms:7700 backoff_types:[regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss]
2018/09/04 14:36:04.067 coprocessor.go:689: [info] [TIME_COP_PROCESS] resp_time:500.519787ms txn_start_ts:402664444484124677 region_id:27 store_addr:172.31.19.224:20160 backoff_ms:8700 backoff_types:[regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss]
2018/09/04 14:36:05.069 coprocessor.go:689: [info] [TIME_COP_PROCESS] resp_time:500.476903ms txn_start_ts:402664444484124677 region_id:27 store_addr:172.31.19.224:20160 backoff_ms:9700 backoff_types:[regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss]
2018/09/04 14:36:06.070 coprocessor.go:689: [info] [TIME_COP_PROCESS] resp_time:500.512217ms txn_start_ts:402664444484124677 region_id:27 store_addr:172.31.19.224:20160 backoff_ms:10700 backoff_types:[regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss]
2018/09/04 14:36:07.071 coprocessor.go:689: [info] [TIME_COP_PROCESS] resp_time:500.487986ms txn_start_ts:402664444484124677 region_id:27 store_addr:172.31.19.224:20160 backoff_ms:11700 backoff_types:[regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss]
2018/09/04 14:36:08.072 coprocessor.go:689: [info] [TIME_COP_PROCESS] resp_time:500.497182ms txn_start_ts:402664444484124677 region_id:27 store_addr:172.31.19.224:20160 backoff_ms:12700 backoff_types:[regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss]
2018/09/04 14:36:09.073 coprocessor.go:689: [info] [TIME_COP_PROCESS] resp_time:500.481278ms txn_start_ts:402664444484124677 region_id:27 store_addr:172.31.19.224:20160 backoff_ms:13700 backoff_types:[regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss,regionMiss]

**Comment by LinuxGit** [comment]
1. Access tidb status page `172.31.26.89:10080` using a web browser, and check if it is OK.
2. Make sure you have disable firewall, or add 10080 to whitelist.
3. Login tidb instances via mysql client, and check if tidb is healthy.

**Comment by gutongjiang** [comment]
@LinuxGit  cannot login tidb because tidb is not start, 10080  port is OK

**Comment by gutongjiang** [comment]
@LinuxGit It's not OK

**Comment by gutongjiang** [comment]
maybe the error is from 
`2018/09/04 16:31:46.085 terror.go:328: [fatal] [tikv:9005]Region is unavailable[try again later]`

**Comment by gutongjiang** [comment]
The firewalld is disabled, I have used this cluster for a few weeks. Today I changed the tikv server and it failed when I started.

**Comment by LinuxGit** [comment]
What's your operation on tikv servers? Are they healthy?

**Comment by gutongjiang** [comment]
I changed some tikv servers, the old machines are terminated

**Comment by LinuxGit** [comment]
@gutongjiang If you want to decrease tikv node, you should take the following steps, see
https://github.com/pingcap/docs/blob/master/op-guide/ansible-deployment-scale.md#decrease-the-capacity-of-a-tikv-node, otherwise the cluster will be abnormal.
