### ISSUE TITLE
remove a tikv node

### ISSUE THREAD

**Issue by gutongjiang** [pingcap/tidb-ansible#523]
I removed a tikv node and check the status

{
  "store": {
    "id": 5,
    "address": "172.31.17.23:20160",
    "state": 1,
    "version": "2.1.0-rc.1",
    "state_name": "Offline"
  },
  "status": {
    "capacity": "197 GiB",
    "available": "188 GiB",
    "leader_count": 207,
    "leader_weight": 1,
    "leader_score": 11288,
    "leader_size": 11288,
    "region_count": 671,
    "region_weight": 1,
    "region_score": 33161,
    "region_size": 33161,
    "start_ts": "2018-09-06T16:59:58+08:00",
    "last_heartbeat_ts": "2018-09-06T18:02:06.640973035+08:00",
    "uptime": "1h2m8.640973035s"
  }
}

Dose it means the node offline success

**Comment by Connor1996** [comment]
Right after use pd-ctl to delete store, the store state is Offline. Then PD will schedule the peers on this store to other stores. When this store has no region anymore, the state will be set to Tombstone which means actual offline successfully.
