### ISSUE TITLE
TiDB没有release版本？

### ISSUE THREAD

**Issue by xtay573269555** [pingcap/tidb-ansible#544]
生产环境是不装git工具的，那要怎么部署TiDB呢？
而且，如果客户使用TiDB（购买商业支持服务），没有release版本号，后续维护如何进行呢？

**Comment by LinuxGit** [comment]
You can use TiDB release-2.0, latest stable version is v2.0.7.
See https://github.com/pingcap/docs-cn/blob/master/op-guide/ansible-deployment.md#在中控机器上下载-tidb-ansible.

You could send email to info@pingcap.com if you have any questions about business service support.
