### ISSUE TITLE
TIDB部署时检测ext4格式硬盘问题

### ISSUE THREAD

**Issue by YcJu** [pingcap/tidb-ansible#546]
我们的服务器硬盘都是ext4的，但是还是出现了报警。
tidb的部署目录是/data/tidb/

fail日志：
[XX.XX.XX.79]: Ansible FAILED! => playbook: deploy.yml; TASK: tikv : Preflight check - Does tikv data dir meet ext4 file system requirement; message: {"changed": false, "msg": "You don't mount the file system of /data with ext4 nodelalloc option. See https://github.com/pingcap/docs/blob/master/op-guide/ansible-deployment.md#mount-the-data-disk-ext4-filesystem-with-options."}

硬盘格式：
# lsblk -f
NAME             FSTYPE      LABEL UUID                                   MOUNTPOINT
sda                                                                       
├─sda1                                                                    
├─sda2           ext4              e198a59d-c96a-425d-ac0a-5e2a6a086817   /boot
└─sda3           LVM2_member       VggxAV-X9as-lQqs-RR8l-WffI-AtCc-768BXz 
  ├─root ext4              dde512c9-746a-44a1-b605-476dbe0fb14b   /
  ├─swap swap              8cdf64e4-e49a-4615-b117-ed7cc60249fb   [SWAP]
  ├─usr  ext4              2a41fa91-914e-4011-80d9-bb3cc4616d3c   /usr
  ├─home ext4              09db8c86-8ea6-4f67-b286-29fea28ac85d   /home
  ├─var  ext4              48bd133a-2157-4cc2-88c0-c47ff7738c4f   /var
  ├─opt  ext4              c3b8f93e-1e5c-476e-929a-f97a9b96bdc1   /opt
  **├─data ext4              a6368509-3879-4901-9bcc-19a44c4d7226   /data**
  └─tmp  ext4              d04fc785-7620-4d7f-99d9-b0f4e2e286d9   /tmp

**Comment by LinuxGit** [comment]
Please add nodelalloc mount option. See https://github.com/pingcap/docs-cn/blob/master/op-guide/ansible-deployment.md#在部署目标机器上添加数据盘-ext4-文件系统挂载参数.

**Comment by YcJu** [comment]
因为我们这是生产环境的机器，/data/下还有其它服务，这么操作会有影响。我的疑惑是，我们的硬盘本来就是ext4了，为啥还会报错？我想手动解决一下，但是找不到可以解决的办法。

**Comment by LinuxGit** [comment]
您好，报错检测是 ext4 文件系统挂载参数。
