### ISSUE TITLE
ansible-playbook deploy.yml   error

### ISSUE THREAD

**Issue by pmzxlpyt** [pingcap/tidb-ansible#549]
TASK [check_system_dynamic : Preflight check - Does every node in cluster have different hostname] ***************************************************************************************************************************************************************************
fatal: [TiKV1]: FAILED! => {"changed": false, "msg": "hostnames of all nodes in cluster: [localhost, localhost, localhost, localhost, localhost, localhost]\n"}

[TiKV1]: Ansible FAILED! => playbook: deploy.yml; TASK: check_system_dynamic : Preflight check - Does every node in cluster have different hostname; message: {"changed": false, "msg": "hostnames of all nodes in cluster: [localhost, localhost, localhost, localhost, localhost, localhost]\n"}

**Comment by LinuxGit** [comment]
Please set different hostname for every server.
