### ISSUE TITLE
why systemd "enabled=no", is there any risk about service auto-restart when machine restart?

### ISSUE THREAD

**Issue by fredchenbj** [pingcap/tidb-ansible#554]
why systemd "enabled=no" in start.yml ?
Is there any risk about services (pd, tikv, tidb, etc.) auto-restart when machine restart?

**Comment by LinuxGit** [comment]
When `enable_binlog = True`,  tidb service depends on pump service's socket file. In the new version of binlog, tidb connects to pump services via tcp port. By the time, we'll set enabled=yes.
