### ISSUE TITLE
Timeout when waiting for search string 200 OK in 192.168.117.244:2379

### ISSUE THREAD

**Issue by pmzxlpyt** [pingcap/tidb-ansible#560]
请问为什么 ansible-playbook start.yml 启动时，有一个pd节点总报错
![image](https://user-images.githubusercontent.com/43162966/46660172-0d8d9080-cbe9-11e8-8a9e-41b1d7ac548c.png)
![image](https://user-images.githubusercontent.com/43162966/46660188-15e5cb80-cbe9-11e8-8ccb-10a6aa33ae2a.png)
而实时上 这个节点中的pd已启动,如下：
![image](https://user-images.githubusercontent.com/43162966/46660274-4a598780-cbe9-11e8-9e40-494ea4268f03.png)

**Comment by LinuxGit** [comment]
Please check pd logs and use pdctl to check pd's heealth.

```
/home/tidb/tidb-ansible/resources/bin/pd-ctl -u "http://192.168.117.243:2379" -d member
/home/tidb/tidb-ansible/resources/bin/pd-ctl -u "http://192.168.117.243:2379" -d health
```

**Comment by pmzxlpyt** [comment]
@LinuxGit  我记起来了，10.1前我将192.168.117.244 这台PD节点移除下线了。所以出现以上问题。请问如何再将此节点添加恢复，重新上线呢？
  inventory.ini 文件中已添加该节点
![image](https://user-images.githubusercontent.com/43162966/46857871-7e78b680-ce3c-11e8-9881-f027c9d606e7.png)

发现log日志提示错误如下：
![image](https://user-images.githubusercontent.com/43162966/46857976-d1526e00-ce3c-11e8-9043-ab236a4f6c4c.png)

**Comment by LinuxGit** [comment]
remove the data of the pd node and rejoin the cluster: 
https://github.com/pingcap/docs-cn/blob/master/op-guide/ansible-deployment-scale.md#扩容-pd-节点
