### ISSUE TITLE
tidb service can not start 

### ISSUE THREAD

**Issue by gongxiucheng** [pingcap/tidb-ansible#592]
run ansible-playbook start.yml,all the other service start successfully,but stop here:

TASK [start TiDB by systemd] *************************************************************************************************************************************************************************************************************************************************
changed: [10.40.20.66]

TASK [wait for TiDB up] ******************************************************************************************************************************************************************************************************************************************************
few seconds later error show up like this:

fatal: [10.40.20.66]: FAILED! => {"changed": false, "elapsed": 300, "msg": "Timeout when waiting for search string TiDB in 10.40.20.66:10080"}
	to retry, use: --limit @/home/tidb/tidb-ansible/retry_files/start.retry

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************************************
10.40.20.66                : ok=11   changed=4    unreachable=0    failed=1   
10.40.20.67                : ok=13   changed=4    unreachable=0    failed=0   
10.40.20.92                : ok=7    changed=2    unreachable=0    failed=0   
TiKV1-1                    : ok=7    changed=1    unreachable=0    failed=0   
TiKV1-2                    : ok=7    changed=1    unreachable=0    failed=0   
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

ERROR MESSAGE SUMMARY ********************************************************************************************************************************************************************************************************************************************************
[10.40.20.66]: Ansible FAILED! => playbook: start.yml; TASK: wait for TiDB up; message: {"changed": false, "elapsed": 300, "msg": "Timeout when waiting for search string TiDB in 10.40.20.66:10080"}

Ask for help:
Contact us: support@pingcap.com

any idea about this ?  need help

**Comment by superlzs0476** [comment]
Hi,That's mean TiDB node 10.40.20.66:10080 can not be start .You  can connect to that one node of start error to check that tidb.log or any abnormal.

**Comment by gongxiucheng** [comment]
much thanks !
