### ISSUE TITLE
error during deploy

### ISSUE THREAD

**Issue by gongxiucheng** [pingcap/tidb-ansible#603]
TASK [check_system_dynamic : Preflight check - Does every node in cluster have different hostname] ***************************************************************************************************************************************************************************
fatal: [10.15.77.184]: FAILED! => {"changed": false, "msg": "hostnames of all nodes in cluster: [tikv, tikv, tidb, tidb, tikv]\n"}

NO MORE HOSTS LEFT ***********************************************************************************************************************************************************************************************************************************************************
	to retry, use: --limit @/home/tidb/tidb-ansible/retry_files/deploy.retry

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************************************
10.15.114.194              : ok=2    changed=0    unreachable=0    failed=0   
10.15.129.27               : ok=2    changed=0    unreachable=0    failed=0   
10.15.4.139                : ok=2    changed=0    unreachable=0    failed=0   
10.15.77.184               : ok=3    changed=0    unreachable=0    failed=1   
10.15.96.169               : ok=2    changed=0    unreachable=0    failed=0   
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

ERROR MESSAGE SUMMARY ********************************************************************************************************************************************************************************************************************************************************
[10.15.77.184]: Ansible FAILED! => playbook: deploy.yml; TASK: check_system_dynamic : Preflight check - Does every node in cluster have different hostname; message: {"changed": false, "msg": "hostnames of all nodes in cluster: [tikv, tikv, tidb, tidb, tikv]\n"}

any idea about this ?  much thanks!

**Comment by superlzs0476** [comment]
TiDB hosts had same hostname，please adjust to different hostname.

**Comment by gongxiucheng** [comment]
> TiDB hosts had same hostname，please a

no place configure the hostname.except /etc/hosts ,hosts.ini and inventory.ini all use ip,not hostname;

**Comment by gongxiucheng** [comment]
> 
> 
> No，that is system configuration .

ok,much thanks!
