### ISSUE TITLE
Sorry, user dba is not allowed to execute '/bin/sh -c echo BECOME-SUCCESS-vjqhlwptxevtxuhigdmthklbkwcgrzsi; /usr/bin/python /home/dba/.ansible/tmp/ansible-tmp-1544178674.23-5388813288913/file.py' as root on

### ISSUE THREAD

**Issue by tozhengxq** [pingcap/tidb-ansible#631]
请问,通过ansible部署时候,部署机器用户为dba,有sudo权限,出现以下错误
能否直接跳过monitor server的安装,只装tidb集群

**//deploy.yml**
- name: deploying node_exporter
  hosts: monitored_servers
  sudo: yes
  tags:
    - node_exporter
  roles:
    - node_exporter

 **» ansible-playbook deploy.yml**
[TIMO2]: Ansible FAILED! => playbook: deploy.yml; TASK: common_dir : create deploy directories; message: {"changed": false, "msg": "All items completed", "results": [{"_ansible_item_result": true, "_ansible_no_log": false, "_ansible_parsed": false, "changed": false, "failed": true, "item": "/home/dba/zxq/tidb/scripts", "module_stderr": "Shared connection to ...... closed.\r\n", "module_stdout": "Sorry, user dba is not allowed to execute '/bin/sh -c echo BECOME-SUCCESS-vjqhlwptxevtxuhigdmthklbkwcgrzsi; /usr/bin/python /home/dba/.ansible/tmp/ansible-tmp-1544178674.23-5388813288913/file.py' as root on ......\r\n", "msg": "MODULE FAILURE", "rc": 1}, {"_ansible_item_result": true, "_ansible_no_log": false, "_ansible_parsed": false, "changed": false, "failed": true, "item": "/home/dba/zxq/tidb/conf", "module_stderr": "Shared connection to ...... closed.\r\n", "module_stdout": "Sorry, user dba is not allowed to execute '/bin/sh -c echo BECOME-SUCCESS-lakhhvjpqjvsgkrmlsndigkuixzlsadn; /usr/bin/python /home/dba/.ansible/tmp/ansible-tmp-1544178674.8-53823180627881/file.py' as root on .........\r\n", "msg": "MODULE FAILURE", "rc": 1}, {"_ansible_item_result": true, "_ansible_no_log": false, "_ansible_parsed": false, "changed": false, "failed": true, "item": "/home/dba/zxq/tidb/backup", "module_stderr": "Shared connection to .... closed.\r\n", "module_stdout": "Sorry, user dba is not allowed to execute '/bin/sh -c echo BECOME-SUCCESS-fgzcdagdypqexysagrkjbalysxdeoqum; /usr/bin/python /home/dba/.ansible/tmp/ansible-tmp-1544178675.3-73358029820092/file.py' as root on  .....\r\n", "msg": "MODULE FAILURE", "rc": 1}]}

**Comment by superlzs0476** [comment]
hi！Please read the deployment documentation carefully and deploy as required. https://pingcap.com/docs-cn/op-guide/ansible-deployment/
