### ISSUE TITLE
the KV stop changing to tombstone state

### ISSUE THREAD

**Issue by jasonshen2011121** [pingcap/tidb-ansible#632]
Hi,
After added 8 KVs to the tidb cluster, the average region is 30K, then I deleted 16 KVs used before to let the cluster drift, and I can see the new 8 KVs region is obvisiouly increasing and old 16 KVs is decreasing in about one week.  But almost when it is done, it stopped drifting, only 1% regions left in the old stores. just hanging for drifting for 3 days. It seems the old 16 KVs will never become tombstone. How can I check the reason? or How can I continue?

Thanks a lot in advance!

**Comment by superlzs0476** [comment]
Hi,
If U want to offline 16 TiKVs from TiDB  cluster ,the best practice is delete TiKVs one by one .The first step is confirm this cluster nodes status is normal ,and then try do it .
Note: It is not recommended to delete multiple TiKVs at the same time, otherwise the cluster cannot schedule so many regions at the same time.

**Comment by jasonshen2011121** [comment]
each 16KVs now only have few regions has not been drifted. How can I break this hanging status? Thanks in advance!!

**Comment by jasonshen2011121** [comment]
» store 18
{
  "store": {
    "id": 18,
    "address": "10.0.26.248:20174",
    "state": 1,
    "labels": [
      {
        "key": "host",
        "value": "tidbkv04"
      }
    ],
    "state_name": "Offline"
  },
  "status": {
    "capacity": "745 GiB",
    "available": "702 GiB",
    "leader_count": 329,
    "leader_weight": 1,
    "leader_score": 33553,
    "leader_size": 33553,
    "region_count": 1070,
    "region_weight": 1,
    "region_score": 110805,
    "region_size": 110805,
    "start_ts": "2018-12-04T14:34:34+08:00",
    "last_heartbeat_ts": "2018-12-11T11:08:45.329497558+08:00",
    "uptime": "164h34m11.329497558s"
  }
}


[tidb@monitor ~]$ pd-ctl -u "http://10.0.25.158:2379" -d store delete 18
Success!

after I ran this command, the region count was still 1070, seems never change anymore.

**Comment by superlzs0476** [comment]
1. check Grafana PD page ，tikv nodes status and rebalance；

**Comment by rleungx** [comment]
Thanks for your feedback! @jasonshen2011121 
Do you have enough space for these 8 KVs? What is your PD and TiKV versions?

**Comment by jasonshen2011121** [comment]
I am sure have enough space left for those regions.
for example of on new KV:
    {
      "store": {
        "id": 1739437,
        "address": "10.0.26.22:20172",
        "labels": [
          {
            "key": "host",
            "value": "tidbkv08"
          }
        ],
        "state_name": "Up"
      },
      "status": {
        "capacity": "1.7 TiB",
        "available": "274 GiB",
        "leader_count": 31213,
        "leader_weight": 1,
        "leader_score": 3448771,
        "leader_size": 3448771,
        "region_count": 93927,
        "region_weight": 1,
        "region_score": 1073461591.3789062,
        "region_size": 10190819,
        "start_ts": "2018-11-30T14:37:47+08:00",
        "last_heartbeat_ts": "2018-12-11T13:54:55.153018742+08:00",
        "uptime": "263h17m8.153018742s"
      }
    },

you see it has 274G left

for the PD and KV version, I don't know how to check.

I only have this:
[tidb@tidbdb01 ~]$ curl http://127.0.0.1:10080/status
{"connections":55,"version":"5.7.10-TiDB-v2.0.7","git_hash":"29ec059cb3b7d14b6f52c2f219f94a89570162bc"}

and I was using ansilbe to deploy the cluster

**Comment by rleungx** [comment]
Currently, we use the percentage of the storage capacity to decide if there is enough space. The default configuration value of `low-space-ratio` is `0.8`, which means if the store's used size over 80% of the whole capacity, the store will be regard as "low space". In this case, the regions won't be moved to this store. 
If you want to make it continue, you can set the `low-space-ratio` to be higher. e.g. 0.9.
```
./pd-ctl -u http://<pd_ip>:<port>
>> config set low-space-ratio 0.9
Success!
```
And you can use 
```
>> config show
```
to check if it works.
BTW, if you want to check the version of your TiKV and PD, you can use:
```
./pd-server --version
./tikv-server --version
```

**Comment by jasonshen2011121** [comment]
多谢，正解！

**Comment by rleungx** [comment]
You're welcome!
