### ISSUE TITLE
cache questions

### ISSUE THREAD

**Issue by weixinqing** [pingcap/tidb-ansible#652]
I have two datasets of the same size。when I open the cache and do the second query in the  MySQL ,I find it fas。 However in Tidb，I have opened the cache and increase cache about 10G ,But In the second query,  tidb is not fast to return a result .I have seen the website of  https://www.pingcap.com/docs-cn/op-guide/tune-tikv/    。Can you help me ?

**Comment by superlzs0476** [comment]
Duplicate issues.
