### ISSUE TITLE
阿里云安装tidb报磁盘iops不符，无法安装

### ISSUE THREAD

**Issue by moka-tantai** [pingcap/tidb-ansible#738]
您好，我这边在阿里云安装tidb运行到

`ansible-playbook bootstrap.yml`

得到如下报错：
![image](https://user-images.githubusercontent.com/47651291/56550834-4efbf100-65b9-11e9-94e9-ea9904dc5ce3.png)

![image](https://user-images.githubusercontent.com/47651291/56551277-7e5f2d80-65ba-11e9-94c1-610a0ee6eb36.png)

图二是已经使用的是阿里云盘的SSD了但是还是没有通过检测。

搜索了一下，有人提供的方案是，使用
`ansible-playbook bootstrap.yml --extra-vars "dev_mode=True"` dev_mode进行安装，这种方法如果在生产环境下是否有安全或者性能的隐患？

**Comment by superlzs0476** [comment]
We strongly recommend installing TiDB  Cluster has to satisfy hardware recommend of the official document. If you deploy the cluster skip hardware and software inspect, the cluster performance will be too slow and we can not provide the technology of support.
We recommend ecs.i2g.4xlarge of aliyun host  use for tikv instance.

**Comment by moka-tantai** [comment]
thanks
