### ISSUE TITLE
ntpd service not enabled

### ISSUE THREAD

**Issue by kolbe** [pingcap/tidb-ansible#749]
I'm doing a tidb-ansible deployment on some CentOS 7 VMs in Azure and it looks like the ntpd service never gets enabled. The result is that "Preflight check - NTP service" fails:

```
fatal: [10.0.1.4]: FAILED! => {"changed": false, "msg": "Make sure NTP service is running and ntpstat is synchronised to NTP server. See https://github.com/pingcap/docs/blob/master/dev/how-to/deploy/orchestrated/ansible.md#how-to-check-whether-the-ntp-service-is-normal ."}
```

Manually enabling & starting the ntpd service allows deploy.yml to complete.

```
ansible -i inventory.ini all -m shell -a 'systemctl enable ntpd ; systemctl start ntpd' -b
```

**Comment by superlzs0476** [comment]
Did you execute the deploy_ntp.yml before deploy TiDB cluster? In the deploy.yml precheck NTP service status. TiDB Cluster needs NTP Service to clock the time of the cluster does not offset too much more.

**Comment by kolbe** [comment]
@superlzs0476 you know, I think I probably missed that step. Thank you!
