### ISSUE TITLE
TiKV's log is too large

### ISSUE THREAD

**Issue by yiran-idea** [pingcap/tidb-ansible#779]
Tikv logs will not be deleted circularly. One of our tikv instance logs reaches 1.4T (4T hard disk).How to set up a fixed number of days, or a fixed size, for tikv logs?

**Comment by liubo0127** [comment]
Currently tikv does not support log deletion, which is related to the development language. Now that we have provided a `clean_log_cron.yml` playbook, you can run `ansible-playbook clean_log_cron.yml --tags=tikv` to set up the tikv log cleanup. The log save time can be set by the `log_retain_days` parameter in `group_vars/all.yml`, and you need to set `enable_log_clean` to true.

**Comment by liubo0127** [comment]
I will close this issue. If this problem is not resolved, you can reopen it.
