### ISSUE TITLE
生产环境完全无法访问外网，怎么部署集群

### ISSUE THREAD

**Issue by sourgelp** [pingcap/tidb-ansible#789]
官网给的ansible几种方式都是需要通过外网下载安装包，而实际情况是生产环境网络控制很严格，完全无法访问外网，怎么完全离线的方式部署集群环境

**Comment by xiamengyu** [comment]
在有外网的机器上执行`ansible-playbook local_prepare.yml`，该脚本会下载所有安装需要的组件。然后将整个tidb-ansible目录打包,传到目标机器执行下一步安装。
其他依赖离线安装：
1、python-pip可以通过yum install下载后离线安装:
`sudo yum install --downloadonly --downloaddir=. python2-pip-8.1.2`
`sudo rpm -ivh python2-pip-8.1.2-8.el7.noarch.rpm`
2、python依赖也可以下载依赖后，离线安装：
`pip install --download /tmp/offline_packages -r requirements.txt`
`pip install --no-index --find-links=file:/tmp/offline_packages -r ./requirements.txt`

**Comment by liubo0127** [comment]
If it is resolved, please close the issue.
