### ISSUE TITLE
Jmespath or Jinja2 does not exist

### ISSUE THREAD

**Issue by jaltabike** [pingcap/tidb-ansible#810]
Deploy TiDB using Ansible (tidb-ansible release-3.0) failed.
When I ran "$ ansible-playbook bootstrap.yml", the check_system_static task failed for target machines.
The error message was as follows:
`"Ansible FAILED! => playbook: bootstrap.yml; TASK: check_system_static : Preflight check - Fail when jmespath or jinja2 doesn't exist; message: {"changed": false, "msg": "Jmespath or Jinja2 does not exist, Please run `pip install -r requirements.txt` to install."}"
`

Checking the existence of jmespath and jinja2 in the control and target machines seems to be added to the check_system_static task from 000fadbd5290c604d8188c6628fd50c678251cac, and this requires jmespath and jinja2 installed not only in the control machine but also in the target machines. But when I follow the installation guide (https://pingcap.com/docs/v3.0/how-to/deploy/orchestrated/ansible/#step-4-install-ansible-and-its-dependencies-on-the-control-machine), jmespath and jinja2 are installed only in the control machine but not int the target machines. Do the target machines need jmespath and jinja2 installed? Then, the installation guide should specify about this.

**Comment by liubo0127** [comment]
Thanks for the feedback, there is a problem here, I will fix it.

**Comment by liubo0127** [comment]
@jaltabike  Fixed, please retry `git clone release-3.0 https://github.com/pingcap/tidb-ansible.git`.

**Comment by jaltabike** [comment]
@liubo0127 Thank you!
It works well now.
