### ISSUE TITLE
v2.1.8 升级到 v3.0.0 后监控图的 Tikv 取不到数据

### ISSUE THREAD

**Issue by wuyanan1993** [pingcap/tidb-ansible#816]
应该是 prometheus 拿到的数据字段内容不一样了，我改了一下grafana 的查询条件后，可以正常显示了，望可以在下一版本修复

**Comment by liubo0127** [comment]
请详细描述一下升级的操作步骤和 TiKV 监控没有数据的现象，也可以提供一些截图信息

**Comment by wuyanan1993** [comment]
升级操作步骤就是按照官网来的，不知道为何升级后grafana 还会有原来的一个dashboard

**Comment by liubo0127** [comment]
在 3.0 版本中 TiKV dashboard 拆分成了 tikv_details、tikv_summary、tikv_trouble_shooting，并且监控数据的收集方式由 push 改成了 pull，原来的 TiKV dashboard 就可以不用看了。

**Comment by liubo0127** [comment]
If it is resolved, please close the issue.
