### ISSUE TITLE
parse prometheus.yml error: did not find expected key

### ISSUE THREAD

**Issue by Jiezhi** [pingcap/tidb-ansible#825]
Deployed with Tag:v2.1.14 and got an error when executed `ansible-playbook start.yml`
```shell
level=error ts=2019-07-15T08:23:40.434383026Z caller=main.go:582 err="Error loading config couldn't load configuration (--config.file=/data/tidb2.1/deploy/conf/prometheus.yml): parsing YAML file /data/tidb2.1/deploy/conf/prometheus.yml: yaml: line 94: did not find expected key"
level=info ts=2019-07-15T08:23:40.434403978Z caller=main.go:584 msg="See you next time!"
```

Obviously the generated `prometheus.yml` file was not right:
```shell
 89   - job_name: "port_probe"
 90     scrape_interval: 30s
 91     metrics_path: /probe
 92     params:
 93       module: [tcp_connect]
 94     static_configs:
 95 - targets:
```
And just add four spaces at line 95 to fix this issue.

I'm not familiar with Jinja, so  fix this [file](https://github.com/pingcap/tidb-ansible/blob/v2.1.14/roles/prometheus/templates/prometheus.yml.j2) would be great.

**Comment by Jiezhi** [comment]
According my test, the `-%` aka [whitespace-control](http://jinja.pocoo.org/docs/2.10/templates/#whitespace-control) would remove all whitespace before the next line content.

**Comment by liubo0127** [comment]
You are right, thanks for your feedback.
