### ISSUE TITLE
Rolling upgrade to v2.1.15 error

### ISSUE THREAD

**Issue by chenleijava** [pingcap/tidb-ansible#836]
Rolling upgrade to v2.1.15, for tispark components, can not find the relevant jar in cp

` playbook: local_prepare.yml; TASK: local : cp tispark; message: {"changed": true, "cmd": "cp -v /home/tidb/tidb-ansible/downloads/core/target/tispark-core-*-SNAPSHOT-jar-with-dependencies.jar \"/home/tidb/tidb-ansible/resources/bin/tispark-SNAPSHOT-jar-with-dependencies.jar\"", "delta": "0:00:00.118299", "end": "2019-07-20 12:36:33.469390", "msg": "non-zero return code", "rc": 1, "start": "2019-07-20 12:36:33.351091", "stderr": "cp: cannot stat ‘/home/tidb/tidb-ansible/downloads/core/target/tispark-core-*-SNAPSHOT-jar-with-dependencies.jar’: No such file or directory", "stderr_lines": ["cp: cannot stat ‘/home/tidb/tidb-ansible/downloads/core/target/tispark-core-*-SNAPSHOT-jar-with-dependencies.jar’: No such file or directory"], "stdout": "", "stdout_lines": []}`

**Comment by liubo0127** [comment]
My local test is normal, please try again. If you still report this error, please check if there is a `tispark jar` file in the `tidb-ansible/downloads/core/target` directory.

**Comment by chenleijava** [comment]
Retry The rolling update was successful, thank you;
