### ISSUE TITLE
Is there a playbook to add/delete pd/tidb/tikv node online?

### ISSUE THREAD

**Issue by george24601** [pingcap/tidb-ansible#95]
[This guide](https://github.com/pingcap/docs/blob/master/op-guide/horizontal-scale.md) shows how to add/delete node online. Is there any playbook to do such thing?

**Comment by LinuxGit** [comment]
See[Scale the TiDB cluster](https://github.com/pingcap/docs/blob/master/QUICKSTART.md#scale-the-tidb-cluster), delete node  is manual.
