### ISSUE TITLE
Alert rules for PD do not respect leadership

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-ansible#982]
Some alert rules for PD do not respect leadership, for example, the rule `sum ( pd_cluster_status{type="store_disconnected_count"}  > 0` will sum up the disconnected store count from both leader and follower, which may cause fake alerts.

**Comment by disksing** [comment]
We have PR aims to fix it too https://github.com/pingcap/pd/pull/1790

**Comment by aylei** [comment]
@disksing Looks good, then do you think it is necessary to modify the alert rules for older versions of PD?

**Comment by disksing** [comment]
Yes. Double-check is better.
